"""Default roles and permission catalog for Pàdéyá."""

# Legacy umbrella codes still referenced by routers/services. Kept for
# backward compatibility; ROLE_PERMISSIONS also grants granular equivalents.
_LEGACY_PERMISSIONS: list[tuple[str, str]] = [
    ("users.read", "Read user profiles"),
    ("users.manage", "Manage users"),
    ("hosts.create", "Create host profiles"),
    ("hosts.manage_own", "Manage own host profile"),
    ("hosts.verify", "Verify host accounts"),
    ("events.manage_own", "Manage own events (umbrella)"),
    ("events.review", "Review event submissions (queue access)"),
    ("payments.view", "View payment records"),
    ("legacy.manage", "Manage Legacy tiers and recalculation"),
    ("memories.moderate", "Moderate event memory pages"),
    ("analytics.view_own", "View own host analytics"),
    ("analytics.view_platform", "View platform analytics"),
    ("analytics.export", "Export analytics CSV"),
    ("ai.use_own", "Use host AI Copilot suggestions"),
    ("ai.use_platform", "Use admin AI Copilot suggestions"),
    ("sponsorships.manage_own", "Manage own sponsorship listings (umbrella)"),
]

_GRANULAR_PERMISSIONS: list[tuple[str, str]] = [
    # Events
    ("events.create", "Create events"),
    ("events.read_own", "Read own events"),
    ("events.update_own", "Update own events"),
    ("events.delete_draft_own", "Discard own draft/rejected events with no sales"),
    ("events.archive_own", "Archive own completed/cancelled events"),
    ("events.cancel_own", "Cancel own events"),
    ("events.submit_review", "Submit own events for review"),
    ("events.approve", "Approve events"),
    ("events.reject", "Reject events"),
    ("events.pause", "Pause published events"),
    ("events.restore", "Resume paused events"),
    # Ticket types
    ("ticket_types.create", "Create ticket types"),
    ("ticket_types.update", "Update ticket types"),
    ("ticket_types.deactivate", "Deactivate ticket types"),
    ("ticket_types.delete_unused", "Hard-delete unused ticket types"),
    # Tickets
    ("tickets.read_own", "Read own tickets"),
    ("tickets.transfer", "Transfer own tickets"),
    ("tickets.cancel", "Cancel own tickets"),
    ("tickets.reissue_qr", "Regenerate ticket QR payloads"),
    ("tickets.scan", "Scan tickets at check-in"),
    ("tickets.manage", "Manage ticket inventory and host ticket ops"),
    # Vault
    ("vault.create", "Create vault items"),
    ("vault.update_own", "Update own vault items"),
    ("vault.archive_own", "Archive own vault items"),
    ("vault.delete_draft_own", "Delete own draft/unpurchased vault items"),
    ("vault.moderate", "Moderate vault content"),
    ("vault.restore", "Restore archived vault items"),
    # Promos
    ("promos.create", "Create promo codes"),
    ("promos.update", "Update promo codes"),
    ("promos.disable", "Disable/deactivate promo codes"),
    ("promos.archive", "Archive promo codes"),
    # Ambassadors
    ("ambassadors.create", "Create ambassadors"),
    ("ambassadors.update", "Update ambassadors"),
    ("ambassadors.deactivate", "Deactivate ambassadors"),
    # Announcements / CRM
    ("announcements.create", "Create announcements"),
    ("announcements.update_draft", "Update draft announcements"),
    ("announcements.send", "Dispatch announcements"),
    ("announcements.archive", "Archive announcements"),
    # Sponsorships
    ("sponsorships.create", "Create sponsorship listings"),
    ("sponsorships.update", "Update sponsorship listings"),
    ("sponsorships.archive", "Archive sponsorship listings"),
    ("sponsorships.moderate", "Moderate sponsorship listings"),
    ("sponsorships.manage_inquiries", "Manage sponsorship inquiries"),
    # Sponsor profiles (workspace identity — not marketplace slots)
    ("sponsors.create", "Create sponsor profiles"),
    ("sponsors.view_own", "View own sponsor profiles"),
    ("sponsors.edit_own", "Edit own sponsor profiles"),
    ("sponsors.manage_team", "Manage sponsor team members"),
    ("sponsors.manage_campaigns", "Manage sponsor campaigns"),
    ("sponsors.view_inquiries", "View sponsor sponsorship inquiries"),
    ("sponsors.save_items", "Save hosts, events, and sponsorship opportunities"),
    ("admin.sponsors.view", "View sponsor profiles in admin"),
    ("admin.sponsors.moderate", "Moderate sponsor profiles and internal notes"),
    ("admin.sponsors.verify", "Verify or reject sponsor profiles"),
    ("admin.sponsors.restrict", "Restrict or suspend sponsor profiles"),
    ("admin.sponsor_campaigns.view", "View sponsor campaigns in admin"),
    ("admin.sponsor_campaigns.moderate", "Approve or reject sponsor campaigns"),
    ("admin.sponsorship_deals.view", "View sponsorship deals in admin"),
    ("admin.sponsorship_deals.manage", "Cancel or resolve sponsorship deals"),
    ("admin.sponsorship_deals.finance", "Void sponsorship invoices"),
    # Reviews
    ("reviews.create", "Create reviews"),
    ("reviews.update_own", "Update own reviews"),
    ("reviews.withdraw_own", "Withdraw own reviews"),
    ("reviews.reply", "Reply to reviews"),
    ("reviews.report", "Report reviews"),
    ("reviews.moderate", "Moderate reviews"),
    # Merch
    ("merch.manage_own", "Manage merch catalog and pricing for own events"),
    ("merch.view_fulfillment", "View merch fulfillment / pickup queues"),
    ("merch.fulfill", "Confirm merch pickup and add desk notes"),
    ("merch.moderate", "Moderate event merchandise listings"),
    ("merch.view_admin", "View merch products and fulfillment for admin/support ops"),
    # Refunds
    ("refunds.create", "Create refund requests"),
    ("refunds.cancel_own", "Cancel own refund requests"),
    ("refunds.review", "View and escalate refund requests"),
    ("refunds.approve", "Approve refunds (financial)"),
    ("refunds.reject", "Reject refunds (financial)"),
    # Payouts
    ("payouts.request", "Request payouts"),
    ("payouts.cancel_own", "Cancel own payout requests"),
    ("payouts.review", "Review payout requests"),
    ("payouts.approve", "Approve payout requests"),
    ("payouts.reject", "Reject payout requests"),
    ("payouts.mark_paid", "Mark payouts as paid (super admin only)"),
    # Support
    ("support.create", "Create support cases"),
    ("support.reply", "Reply to support cases"),
    ("support.assign", "Assign support cases"),
    ("support.escalate", "Escalate support cases"),
    ("support.resolve", "Resolve support cases"),
    ("support.archive", "Archive support cases"),
    ("admin.support.view", "View support tickets"),
    ("admin.support.reply", "Reply to support tickets"),
    ("admin.support.assign", "Assign support tickets"),
    ("admin.support.resolve", "Resolve support tickets"),
    ("admin.support.close", "Close support tickets"),
    ("admin.support.internal_notes", "Add internal support notes"),
    ("admin.support.manage_settings", "Manage support center settings"),
    ("admin.support.view_all", "View all support tickets across queues"),
    ("admin.support.delete_attachment", "Delete support ticket attachments"),
    # Fan Connect
    ("fan_connect.use", "Use Fan Connect requests and connections"),
    # Admin
    ("admin.full_access", "Full administrative access"),
    ("admin.emails.view", "View admin platform email templates"),
    ("admin.emails.edit_templates", "Edit admin platform email templates"),
    ("admin.emails.test_send", "Send admin email template tests"),
    ("admin.emails.manage_recipients", "Manage admin email recipient groups"),
    ("admin.notifications.view", "View admin notification settings and campaigns"),
    (
        "admin.notifications.manage_settings",
        "Manage notification type toggles and templates",
    ),
    ("admin.notifications.send_custom", "Compose and send custom admin notifications"),
    (
        "admin.notifications.view_delivery_logs",
        "View notification delivery logs",
    ),
    ("admin.users.view", "View admin user directory and account details"),
    (
        "admin.users.view_private_contact",
        "View unmasked email/phone on admin user records",
    ),
    (
        "admin.users.view_activity",
        "View admin user activity counters and related slices",
    ),
    (
        "admin.users.view_security",
        "View admin user security lock details and session counts",
    ),
    ("admin.users.add_note", "Add internal admin notes on users"),
    ("admin.users.flag", "Add and resolve/dismiss admin user flags"),
    (
        "admin.users.restrict",
        "Legacy umbrella: under-review + selective restrictions (implies granular)",
    ),
    (
        "admin.users.view_restrictions",
        "View user restriction history (active, revoked, expired)",
    ),
    (
        "admin.users.add_restriction",
        "Add or extend selective user restriction rows",
    ),
    (
        "admin.users.revoke_restriction",
        "Revoke selective user restriction rows",
    ),
    ("admin.users.suspend", "Suspend and unsuspend user accounts"),
    ("admin.users.ban", "Ban and unban user accounts"),
    (
        "admin.appeals.review",
        "Review account suspension appeals (approve / reject)",
    ),
    ("admin.users.force_logout", "Force-logout all refresh sessions for a user"),
    (
        "admin.users.force_password_reset",
        "Force-send a password reset email for a user",
    ),
    ("admin.users.view_audit", "View per-user admin audit history"),
    (
        "admin.users.impersonate",
        "Start audited admin user impersonation sessions (view pack)",
    ),
    (
        "admin.users.impersonate.host_events",
        "Include host event studio mutations in impersonation sessions",
    ),
    ("admin.events.view", "View admin event buyers / attendees lists"),
    (
        "admin.events.export_buyers",
        "Export admin event buyer/attendee CSV or JSON",
    ),
    (
        "admin.events.export_private_contact",
        "Include buyer email/phone in admin event buyer exports",
    ),
    (
        "admin.finance.export_event_sales",
        "Export admin event buyer finance-depth fields",
    ),
    (
        "admin.finance.view_fees",
        "View platform fee settings and host fee overrides",
    ),
    (
        "admin.finance.manage_fees",
        "Create and update platform fee settings",
    ),
    (
        "admin.finance.manage_host_overrides",
        "Create and update host-specific fee overrides",
    ),
    # Admin Runtime Settings
    ("admin.settings.view", "View admin runtime settings (non-secret values)"),
    (
        "admin.settings.edit_runtime",
        "Edit non-secret admin runtime settings overrides",
    ),
    (
        "admin.settings.edit_secrets",
        "Replace or clear admin-managed runtime secrets",
    ),
    (
        "admin.settings.test_integrations",
        "Run safe admin runtime settings integration tests",
    ),
    (
        "admin.settings.view_system_status",
        "View safe system status (configured flags only)",
    ),
    (
        "admin.settings.clear_overrides",
        "Clear DB runtime setting overrides back to env/default",
    ),
    (
        "admin.settings.view_audit",
        "View runtime settings audit log entries",
    ),
    # Admin AI controls
    ("admin.ai.view", "View Pàdéyá AI admin controls overview"),
    ("admin.ai.manage_settings", "Manage AI global switch and platform spend caps"),
    ("admin.ai.manage_providers", "Manage AI provider profiles"),
    ("admin.ai.manage_features", "Manage per-feature AI routing and limits"),
    ("admin.ai.manage_safety", "View AI safety controls"),
    ("admin.ai.manage_spend", "Manage AI spend caps and thresholds"),
    ("admin.ai.view_usage", "View AI usage dashboard aggregates"),
    ("admin.ai.test_connection", "Run AI provider test connection"),
    ("admin.ai.view_logs", "View safe AI generation logs"),
    # Platform maintenance
    ("admin.maintenance.view", "View platform maintenance controls and history"),
    ("admin.maintenance.manage", "Enable/disable maintenance and section controls"),
    ("admin.maintenance.schedule", "Create and cancel maintenance schedules"),
    ("admin.maintenance.notify", "Send maintenance advance notifications"),
    ("admin.maintenance.bypass", "Generate and use maintenance bypass sessions"),
    (
        "admin.platform.view_readiness",
        "View production readiness preflight (read-only)",
    ),
    ("admin.blog.view", "View blog CMS"),
    ("admin.blog.create", "Create blog posts"),
    ("admin.blog.edit", "Edit blog posts, categories, tags, authors"),
    ("admin.blog.publish", "Publish and unpublish blog posts"),
    ("admin.blog.delete", "Archive/delete blog posts"),
    ("blog.comments.edit_own", "Edit own blog comments"),
    ("blog.comments.reply", "Reply to blog comments"),
    ("admin.blog.comments.edit_any", "Edit any blog comment"),
    ("admin.blog.comments.reply_any", "Reply to any blog comment as staff"),
    ("admin.blog.comments.moderate", "Moderate and edit blog comments"),
    # Knowledge Base / Help Center
    ("admin.knowledge_base.view", "View knowledge base CMS"),
    ("admin.knowledge_base.create", "Create knowledge base articles"),
    ("admin.knowledge_base.edit", "Edit knowledge base articles and tags"),
    ("admin.knowledge_base.publish", "Publish and unpublish knowledge base articles"),
    ("admin.knowledge_base.archive", "Archive knowledge base articles"),
    (
        "admin.knowledge_base.manage_categories",
        "Create and edit knowledge base categories",
    ),
    # Admin Team Management
    ("admin.team.view", "View platform admin team members and roles"),
    ("admin.team.invite", "Invite platform admin team members"),
    (
        "admin.team.manage_members",
        "Edit, disable, or remove platform admin team members",
    ),
    (
        "admin.team.manage_roles",
        "Create and edit custom admin roles and permission sets",
    ),
    (
        "admin.team.force_logout",
        "Force-logout platform admin team members",
    ),
    ("admin.team.view_audit", "View admin team activity and audit logs"),
]

DEFAULT_PERMISSIONS: list[tuple[str, str]] = [
    *_LEGACY_PERMISSIONS,
    *_GRANULAR_PERMISSIONS,
]

# Holding an umbrella permission satisfies these granular checks.
PERMISSION_IMPLIES: dict[str, frozenset[str]] = {
    "admin.blog.edit": frozenset(
        {
            "admin.blog.comments.edit_any",
            "admin.blog.comments.reply_any",
            "admin.blog.comments.moderate",
        }
    ),
    "admin.blog.comments.moderate": frozenset(
        {
            "admin.blog.comments.edit_any",
            "admin.blog.comments.reply_any",
        }
    ),
    "events.manage_own": frozenset(
        {
            "events.read_own",
            "events.update_own",
            "events.delete_draft_own",
            "events.archive_own",
            "events.cancel_own",
            "events.submit_review",
            "events.pause",
            "events.restore",
            "ticket_types.create",
            "ticket_types.update",
            "ticket_types.deactivate",
            "ticket_types.delete_unused",
        }
    ),
    "sponsorships.manage_own": frozenset(
        {
            "sponsorships.create",
            "sponsorships.update",
            "sponsorships.archive",
            "sponsorships.manage_inquiries",
        }
    ),
    "vault.create": frozenset(
        {
            "vault.update_own",
            "vault.archive_own",
            "vault.delete_draft_own",
            "vault.restore",
        }
    ),
    "refunds.approve": frozenset({"refunds.reject"}),
    "support.reply": frozenset(
        {
            "support.assign",
            "support.escalate",
            "support.resolve",
            "support.archive",
            "admin.support.view",
            "admin.support.reply",
            "admin.support.assign",
            "admin.support.resolve",
            "admin.support.close",
            "admin.support.internal_notes",
            "admin.support.view_all",
            "admin.support.delete_attachment",
        }
    ),
    "admin.support.view_all": frozenset({"admin.support.view"}),
    "admin.support.reply": frozenset({"admin.support.view"}),
    "admin.support.assign": frozenset({"admin.support.view"}),
    "admin.support.resolve": frozenset(
        {"admin.support.view", "admin.support.close"}
    ),
    "admin.support.internal_notes": frozenset({"admin.support.view"}),
    "admin.support.manage_settings": frozenset({"admin.support.view"}),
    "admin.support.delete_attachment": frozenset({"admin.support.view"}),
    "merch.manage_own": frozenset(
        {
            "merch.view_fulfillment",
            "merch.fulfill",
        }
    ),
    "merch.fulfill": frozenset({"merch.view_fulfillment"}),
    "admin.finance.manage_fees": frozenset({"admin.finance.view_fees"}),
    "admin.finance.manage_host_overrides": frozenset({"admin.finance.view_fees"}),
    "admin.ai.manage_settings": frozenset(
        {
            "admin.ai.test_connection",
            "admin.ai.manage_spend",
        }
    ),
    "admin.settings.edit_runtime": frozenset(
        {
            "admin.ai.manage_settings",
            "admin.ai.manage_providers",
            "admin.ai.test_connection",
        }
    ),
    # Directory view unlocks activity/audit slices; private contact + security stay separate.
    "admin.users.view": frozenset(
        {
            "admin.users.view_activity",
            "admin.users.view_audit",
            "admin.users.view_restrictions",
        }
    ),
    # Legacy umbrella still satisfies granular restriction permissions.
    "admin.users.restrict": frozenset(
        {
            "admin.users.view_restrictions",
            "admin.users.add_restriction",
            "admin.users.revoke_restriction",
        }
    ),
}

DEFAULT_ROLES: dict[str, str] = {
    "buyer": "Default attendee / ticket buyer",
    "host": "Event host / creator",
    "host_staff": "Host team member with limited tools",
    "sponsor": "Sponsor / brand workspace owner",
    "support_agent": "Customer support agent",
    "finance_admin": "Finance and payouts administrator",
    "admin": "Platform administrator (not super admin)",
    "moderation": "Content and community moderation",
    "operations": "Platform operations",
    "marketing": "Marketing and campaigns",
    "admin_staff": "Platform admin staff (workspace access)",
    "super_admin": "Platform super administrator",
}

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "buyer": [
        "tickets.read_own",
        "tickets.transfer",
        "tickets.cancel",
        "tickets.reissue_qr",
        "reviews.create",
        "reviews.update_own",
        "reviews.withdraw_own",
        "reviews.report",
        "refunds.create",
        "refunds.cancel_own",
        "support.create",
        "fan_connect.use",
        "blog.comments.edit_own",
        "blog.comments.reply",
    ],
    "host": [
        "hosts.create",
        "hosts.manage_own",
        # Events (umbrella + explicit granular for clarity in /me permissions)
        "events.create",
        "events.manage_own",
        "events.read_own",
        "events.update_own",
        "events.delete_draft_own",
        "events.archive_own",
        "events.cancel_own",
        "events.submit_review",
        "events.pause",
        "events.restore",
        "ticket_types.create",
        "ticket_types.update",
        "ticket_types.deactivate",
        "ticket_types.delete_unused",
        "tickets.scan",
        "tickets.manage",
        "payments.view",
        "payouts.request",
        "payouts.cancel_own",
        "reviews.reply",
        "reviews.report",
        "blog.comments.edit_own",
        "blog.comments.reply",
        "vault.create",
        "vault.update_own",
        "vault.archive_own",
        "vault.delete_draft_own",
        "vault.restore",
        "promos.create",
        "promos.update",
        "promos.disable",
        "promos.archive",
        "ambassadors.create",
        "ambassadors.update",
        "ambassadors.deactivate",
        "announcements.create",
        "announcements.update_draft",
        "announcements.send",
        "announcements.archive",
        "sponsorships.manage_own",
        "sponsorships.create",
        "sponsorships.update",
        "sponsorships.archive",
        "sponsorships.manage_inquiries",
        "analytics.view_own",
        "analytics.export",
        "ai.use_own",
        "support.create",
        "merch.manage_own",
        "merch.view_fulfillment",
        "merch.fulfill",
        "fan_connect.use",
    ],
    "host_staff": [
        "events.manage_own",
        "events.read_own",
        "events.update_own",
        "tickets.scan",
        "tickets.manage",
        "ticket_types.update",
        "ticket_types.deactivate",
        "reviews.reply",
        # Desk pickup only — not catalog/pricing (needs merch.manage_own + host ownership)
        "merch.view_fulfillment",
        "merch.fulfill",
    ],
    "sponsor": [
        "sponsors.create",
        "sponsors.view_own",
        "sponsors.edit_own",
        "sponsors.manage_team",
        "sponsors.manage_campaigns",
        "sponsors.view_inquiries",
        "sponsors.save_items",
    ],
    "support_agent": [
        # User management MVP: view directory + add notes only (no suspend/flag by default).
        "admin.users.view",
        "admin.users.add_note",
        "hosts.verify",
        "support.create",
        "support.reply",
        "support.assign",
        "support.escalate",
        "support.resolve",
        "support.archive",
        "admin.support.view",
        "admin.support.reply",
        "admin.support.assign",
        "admin.support.resolve",
        "admin.support.close",
        "admin.support.internal_notes",
        "admin.support.view_all",
        "admin.support.delete_attachment",
        "admin.support.manage_settings",
        "reviews.moderate",
        # View merch ops for support; cannot hide/remove listings (no merch.moderate)
        "merch.view_admin",
        "events.review",
        "events.approve",
        "events.reject",
        "refunds.review",
        # vault.moderate / vault.restore intentionally omitted —
        # support cannot moderate Vault unless granted the permission
        # payments.view / refunds.approve intentionally omitted — no ledger edits
        "memories.moderate",
        "analytics.view_platform",
        "ai.use_platform",
        "sponsorships.moderate",
        "admin.sponsors.view",
        "admin.sponsors.moderate",
        "admin.sponsors.verify",
        "admin.sponsors.restrict",
        "admin.sponsor_campaigns.view",
        "admin.sponsor_campaigns.moderate",
        "admin.sponsorship_deals.view",
        "admin.sponsorship_deals.manage",
        # admin.sponsorship_deals.finance intentionally omitted —
        # support cannot void invoices / modify financial records
        "admin.events.view",
        "admin.events.export_buyers",
        "admin.events.export_private_contact",
        # Runtime settings — view safe status only (no edits / secrets)
        "admin.settings.view",
        "admin.settings.view_system_status",
        "admin.appeals.review",
        "admin.maintenance.view",
    ],
    "finance_admin": [
        # No admin.users.* by default — grant explicitly if needed.
        # admin.users.impersonate intentionally omitted — finance cannot impersonate
        "payments.view",
        "refunds.review",
        "refunds.approve",
        "refunds.reject",
        "payouts.review",
        "payouts.approve",
        "payouts.reject",
        # payouts.mark_paid intentionally omitted — super_admin only
        "legacy.manage",
        "vault.moderate",
        "memories.moderate",
        "analytics.view_platform",
        "analytics.export",
        "ai.use_platform",
        "sponsorships.moderate",
        "admin.sponsors.view",
        "admin.sponsors.moderate",
        "admin.sponsors.verify",
        "admin.sponsors.restrict",
        "admin.sponsor_campaigns.view",
        "admin.sponsor_campaigns.moderate",
        "admin.sponsorship_deals.view",
        "admin.sponsorship_deals.manage",
        "admin.sponsorship_deals.finance",
        "admin.events.view",
        "admin.events.export_buyers",
        "admin.finance.export_event_sales",
        "admin.finance.view_fees",
        "admin.finance.manage_fees",
        "admin.finance.manage_host_overrides",
        "admin.support.view",
        "admin.support.reply",
        "admin.support.internal_notes",
        # Runtime settings — can edit non-secret payment tunables (not secrets)
        "admin.settings.view",
        "admin.settings.view_system_status",
        "admin.settings.edit_runtime",
    ],
    "admin": [
        "admin.users.view",
        "admin.users.view_private_contact",
        "admin.users.view_activity",
        "admin.users.view_security",
        "admin.users.add_note",
        "admin.users.flag",
        "admin.users.restrict",
        "admin.users.suspend",
        "admin.users.force_logout",
        "admin.users.force_password_reset",
        "admin.users.view_audit",
        "admin.users.impersonate",
        "admin.users.impersonate.host_events",
        "admin.appeals.review",
        "hosts.verify",
        "events.review",
        "events.approve",
        "events.reject",
        "events.pause",
        "events.restore",
        "support.create",
        "support.reply",
        "reviews.moderate",
        "merch.view_admin",
        "memories.moderate",
        "sponsorships.moderate",
        "admin.sponsors.view",
        "admin.sponsors.moderate",
        "admin.sponsors.verify",
        "admin.sponsors.restrict",
        "admin.sponsor_campaigns.view",
        "admin.sponsor_campaigns.moderate",
        "admin.sponsorship_deals.view",
        "admin.sponsorship_deals.manage",
        "admin.sponsorship_deals.finance",
        "admin.events.view",
        "admin.events.export_buyers",
        "admin.notifications.view",
        "admin.notifications.manage_settings",
        "admin.notifications.send_custom",
        "admin.notifications.view_delivery_logs",
        "admin.settings.view",
        "admin.settings.view_system_status",
        "admin.settings.edit_runtime",
        "admin.ai.view",
        "admin.ai.manage_settings",
        "admin.ai.manage_providers",
        "admin.ai.manage_features",
        "admin.ai.manage_safety",
        "admin.ai.manage_spend",
        "admin.ai.view_usage",
        "admin.ai.test_connection",
        "admin.ai.view_logs",
        "admin.maintenance.view",
        "admin.maintenance.manage",
        "admin.maintenance.schedule",
        "admin.maintenance.notify",
        "admin.maintenance.bypass",
        "admin.blog.view",
        "admin.blog.create",
        "admin.blog.edit",
        "admin.blog.publish",
        "admin.blog.delete",
        "admin.blog.comments.edit_any",
        "admin.blog.comments.reply_any",
        "admin.blog.comments.moderate",
        "admin.knowledge_base.view",
        "admin.knowledge_base.create",
        "admin.knowledge_base.edit",
        "admin.knowledge_base.publish",
        "admin.knowledge_base.archive",
        "admin.knowledge_base.manage_categories",
        "admin.support.view",
        "admin.support.reply",
        "admin.support.assign",
        "admin.support.resolve",
        "admin.support.close",
        "admin.support.internal_notes",
        "admin.support.view_all",
        "admin.support.delete_attachment",
        "admin.support.manage_settings",
        "admin.team.view",
        "admin.team.invite",
        "admin.team.manage_members",
        "admin.team.manage_roles",
        "admin.team.force_logout",
        "admin.team.view_audit",
        "analytics.view_platform",
        "ai.use_platform",
        # No admin.full_access / edit_secrets / payouts.mark_paid / ban by default
    ],
    "moderation": [
        "admin.users.view",
        "admin.users.add_note",
        "admin.users.flag",
        "admin.users.view_restrictions",
        "admin.appeals.review",
        "admin.support.view",
        "admin.support.internal_notes",
        "admin.support.assign",
        "events.review",
        "events.approve",
        "events.reject",
        "events.pause",
        "reviews.moderate",
        "memories.moderate",
        "sponsorships.moderate",
        "admin.sponsors.view",
        "admin.sponsors.moderate",
        "admin.sponsors.verify",
        "admin.sponsors.restrict",
        "admin.sponsor_campaigns.view",
        "admin.sponsor_campaigns.moderate",
        "admin.sponsorship_deals.view",
        "admin.sponsorship_deals.manage",
        # admin.sponsorship_deals.finance intentionally omitted — no finance mutations
        "merch.moderate",
        "vault.moderate",
        "support.reply",
        "admin.events.view",
        "admin.blog.view",
        "admin.blog.comments.edit_any",
        "admin.blog.comments.reply_any",
        "admin.blog.comments.moderate",
        # No finance / impersonation by default
    ],
    "operations": [
        "admin.users.view",
        "admin.users.add_note",
        "admin.users.impersonate",
        "admin.users.impersonate.host_events",
        "hosts.verify",
        "events.review",
        "events.approve",
        "events.reject",
        "support.create",
        "support.reply",
        "merch.view_admin",
        "admin.events.view",
        "admin.settings.view",
        "admin.settings.view_system_status",
        "admin.ai.view",
        "admin.ai.manage_settings",
        "admin.ai.test_connection",
        # No finance / credentials impersonation by default
    ],
    "marketing": [
        "announcements.create",
        "announcements.update_draft",
        "announcements.send",
        "announcements.archive",
        "admin.notifications.view",
        "admin.notifications.send_custom",
        "admin.blog.view",
        "admin.blog.create",
        "admin.blog.edit",
        "admin.blog.publish",
        "admin.knowledge_base.view",
        "admin.knowledge_base.create",
        "admin.knowledge_base.edit",
        "admin.knowledge_base.publish",
        "analytics.view_platform",
        "admin.users.view",
        # No finance / impersonation / team manage by default
    ],
    "admin_staff": [],
    "super_admin": ["admin.full_access"],
}

DEFAULT_REGISTER_ROLE = "buyer"

# Canonical codes from the product permission matrix (must stay seeded).
REQUIRED_PERMISSION_CODES: frozenset[str] = frozenset(
    {
        "events.create",
        "events.read_own",
        "events.update_own",
        "events.delete_draft_own",
        "events.archive_own",
        "events.cancel_own",
        "events.submit_review",
        "events.approve",
        "events.reject",
        "events.pause",
        "events.restore",
        "ticket_types.create",
        "ticket_types.update",
        "ticket_types.deactivate",
        "ticket_types.delete_unused",
        "tickets.read_own",
        "tickets.transfer",
        "tickets.cancel",
        "tickets.reissue_qr",
        "tickets.scan",
        "tickets.manage",
        "vault.create",
        "vault.update_own",
        "vault.archive_own",
        "vault.delete_draft_own",
        "vault.moderate",
        "vault.restore",
        "promos.create",
        "promos.update",
        "promos.disable",
        "promos.archive",
        "ambassadors.create",
        "ambassadors.update",
        "ambassadors.deactivate",
        "announcements.create",
        "announcements.update_draft",
        "announcements.send",
        "announcements.archive",
        "sponsorships.create",
        "sponsorships.update",
        "sponsorships.archive",
        "sponsorships.moderate",
        "sponsorships.manage_inquiries",
        "reviews.create",
        "reviews.update_own",
        "reviews.withdraw_own",
        "reviews.reply",
        "reviews.report",
        "reviews.moderate",
        "blog.comments.edit_own",
        "blog.comments.reply",
        "admin.blog.comments.edit_any",
        "admin.blog.comments.reply_any",
        "admin.blog.comments.moderate",
        "merch.manage_own",
        "merch.view_fulfillment",
        "merch.fulfill",
        "merch.moderate",
        "merch.view_admin",
        "refunds.create",
        "refunds.cancel_own",
        "refunds.review",
        "refunds.approve",
        "refunds.reject",
        "payouts.request",
        "payouts.cancel_own",
        "payouts.review",
        "payouts.approve",
        "payouts.reject",
        "payouts.mark_paid",
        "support.create",
        "support.reply",
        "support.assign",
        "support.escalate",
        "support.resolve",
        "support.archive",
        "admin.full_access",
        "admin.emails.view",
        "admin.emails.edit_templates",
        "admin.emails.test_send",
        "admin.emails.manage_recipients",
        "admin.notifications.view",
        "admin.notifications.manage_settings",
        "admin.notifications.send_custom",
        "admin.notifications.view_delivery_logs",
        "admin.users.view",
        "admin.users.view_private_contact",
        "admin.users.view_activity",
        "admin.users.view_security",
        "admin.users.add_note",
        "admin.users.flag",
        "admin.users.restrict",
        "admin.users.view_restrictions",
        "admin.users.add_restriction",
        "admin.users.revoke_restriction",
        "admin.users.suspend",
        "admin.users.ban",
        "admin.appeals.review",
        "admin.users.force_logout",
        "admin.users.force_password_reset",
        "admin.users.view_audit",
        "admin.users.impersonate",
        "admin.events.view",
        "admin.events.export_buyers",
        "admin.events.export_private_contact",
        "admin.finance.export_event_sales",
        "admin.finance.view_fees",
        "admin.finance.manage_fees",
        "admin.finance.manage_host_overrides",
        "admin.settings.view",
        "admin.settings.edit_runtime",
        "admin.settings.edit_secrets",
        "admin.settings.test_integrations",
        "admin.settings.view_system_status",
        "admin.settings.clear_overrides",
        "admin.settings.view_audit",
        "admin.ai.view",
        "admin.ai.manage_settings",
        "admin.ai.manage_providers",
        "admin.ai.manage_features",
        "admin.ai.manage_safety",
        "admin.ai.manage_spend",
        "admin.ai.view_usage",
        "admin.ai.test_connection",
        "admin.ai.view_logs",
        "admin.maintenance.view",
        "admin.maintenance.manage",
        "admin.maintenance.schedule",
        "admin.maintenance.notify",
        "admin.maintenance.bypass",
        "admin.blog.view",
        "admin.blog.create",
        "admin.blog.edit",
        "admin.blog.publish",
        "admin.blog.delete",
        "admin.blog.comments.edit_any",
        "admin.blog.comments.reply_any",
        "admin.blog.comments.moderate",
        "admin.knowledge_base.view",
        "admin.knowledge_base.create",
        "admin.knowledge_base.edit",
        "admin.knowledge_base.publish",
        "admin.knowledge_base.archive",
        "admin.knowledge_base.manage_categories",
        "admin.team.view",
        "admin.team.invite",
        "admin.team.manage_members",
        "admin.team.manage_roles",
        "admin.team.force_logout",
        "admin.team.view_audit",
    }
)

# Curated permission codes for the admin role/permission builder UI.
ADMIN_TEAM_PERMISSION_GROUPS: list[tuple[str, list[str]]] = [
    (
        "Users",
        [
            "admin.users.view",
            "admin.users.view_private_contact",
            "admin.users.view_activity",
            "admin.users.view_security",
            "admin.users.add_note",
            "admin.users.flag",
            "admin.users.view_restrictions",
            "admin.users.add_restriction",
            "admin.users.revoke_restriction",
            "admin.users.restrict",
            "admin.users.suspend",
            "admin.users.ban",
            "admin.users.force_logout",
            "admin.users.force_password_reset",
            "admin.users.view_audit",
            "admin.users.impersonate",
            "admin.users.impersonate.host_events",
        ],
    ),
    (
        "Appeals & support",
        [
            "admin.appeals.review",
            "support.create",
            "support.reply",
            "support.assign",
            "support.escalate",
            "support.resolve",
            "support.archive",
        ],
    ),
    (
        "Events & hosts",
        [
            "events.review",
            "events.approve",
            "events.reject",
            "events.pause",
            "events.restore",
            "hosts.verify",
            "admin.events.view",
            "admin.events.export_buyers",
            "admin.events.export_private_contact",
        ],
    ),
    (
        "Moderation",
        [
            "reviews.moderate",
            "memories.moderate",
            "sponsorships.moderate",
            "merch.moderate",
            "merch.view_admin",
            "vault.moderate",
            "vault.restore",
        ],
    ),
    (
        "Finance & revenue",
        [
            "payments.view",
            "refunds.review",
            "refunds.approve",
            "refunds.reject",
            "payouts.review",
            "payouts.approve",
            "payouts.reject",
            "payouts.mark_paid",
            "admin.finance.export_event_sales",
            "admin.finance.view_fees",
            "admin.finance.manage_fees",
            "admin.finance.manage_host_overrides",
            "legacy.manage",
        ],
    ),
    (
        "Notifications & marketing",
        [
            "admin.notifications.view",
            "admin.notifications.manage_settings",
            "admin.notifications.send_custom",
            "admin.notifications.view_delivery_logs",
            "announcements.create",
            "announcements.update_draft",
            "announcements.send",
            "announcements.archive",
        ],
    ),
    (
        "Admin settings",
        [
            "admin.settings.view",
            "admin.settings.view_system_status",
            "admin.settings.edit_runtime",
            "admin.settings.edit_secrets",
            "admin.settings.test_integrations",
            "admin.settings.clear_overrides",
            "admin.settings.view_audit",
            "admin.ai.view",
            "admin.ai.manage_settings",
            "admin.ai.manage_providers",
            "admin.ai.manage_features",
            "admin.ai.manage_safety",
            "admin.ai.manage_spend",
            "admin.ai.view_usage",
            "admin.ai.test_connection",
            "admin.ai.view_logs",
            "admin.maintenance.view",
            "admin.maintenance.manage",
            "admin.maintenance.schedule",
            "admin.maintenance.notify",
            "admin.maintenance.bypass",
            "admin.blog.view",
            "admin.blog.create",
            "admin.blog.edit",
            "admin.blog.publish",
            "admin.blog.delete",
            "admin.blog.comments.edit_any",
            "admin.blog.comments.reply_any",
            "admin.blog.comments.moderate",
            "admin.knowledge_base.view",
            "admin.knowledge_base.create",
            "admin.knowledge_base.edit",
            "admin.knowledge_base.publish",
            "admin.knowledge_base.archive",
            "admin.knowledge_base.manage_categories",
            "admin.support.view",
            "admin.support.reply",
            "admin.support.assign",
            "admin.support.resolve",
            "admin.support.close",
            "admin.support.internal_notes",
            "admin.support.view_all",
            "admin.support.delete_attachment",
            "admin.support.manage_settings",
        ],
    ),
    (
        "Team management",
        [
            "admin.team.view",
            "admin.team.invite",
            "admin.team.manage_members",
            "admin.team.manage_roles",
            "admin.team.force_logout",
            "admin.team.view_audit",
        ],
    ),
]

# Only super_admin may assign these to custom roles or invite as system keys.
ADMIN_TEAM_HIGH_LEVEL_PERMISSIONS: frozenset[str] = frozenset(
    {
        "admin.full_access",
        "admin.settings.edit_secrets",
        "payouts.mark_paid",
        "admin.users.ban",
    }
)

ADMIN_TEAM_HIGH_LEVEL_SYSTEM_KEYS: frozenset[str] = frozenset(
    {"super_admin", "admin"}
)

# Maps admin_roles.system_key → seeded Role.name
ADMIN_TEAM_SYSTEM_ROLE_LINKS: dict[str, str] = {
    "super_admin": "super_admin",
    "admin": "admin",
    "support": "support_agent",
    "moderation": "moderation",
    "finance": "finance_admin",
    "operations": "operations",
    "marketing": "marketing",
}

ADMIN_TEAM_SYSTEM_ROLE_META: dict[str, tuple[str, str]] = {
    "super_admin": ("Super Admin", "Full platform control"),
    "admin": ("Admin", "Platform administrator without super-admin privileges"),
    "support": ("Support", "Customer support and appeals"),
    "moderation": ("Moderation", "Content and community moderation"),
    "finance": ("Finance", "Payments, refunds, and payouts"),
    "operations": ("Operations", "Hosts, events, and day-to-day ops"),
    "marketing": ("Marketing", "Campaigns and announcements"),
}
