import type { CmsBrowseRail } from "@/lib/types/lifecycle";

export type BrowseTileLink = {
  rail: CmsBrowseRail;
  label: string;
  hint: string;
  href: string;
  image: string;
  sort_order: number;
};

/** Fallback when CMS has no published browse tiles yet. */
export const DEFAULT_BROWSE_TILES: BrowseTileLink[] = [
  {
    rail: "interest",
    label: "Nightlife & parties",
    hint: "Detty · club nights",
    href: "/events/c/nightlife",
    image: "/brand/browse/nightlife.svg",
    sort_order: 0,
  },
  {
    rail: "interest",
    label: "Concerts & live shows",
    hint: "Afrobeats · stages",
    href: "/events/c/music",
    image: "/brand/browse/music.svg",
    sort_order: 1,
  },
  {
    rail: "interest",
    label: "Comedy",
    hint: "Open mics · headliners",
    href: "/events/c/comedy",
    image: "/brand/browse/comedy.svg",
    sort_order: 2,
  },
  {
    rail: "interest",
    label: "Tech & business",
    hint: "Mixers · demos",
    href: "/events/c/tech",
    image: "/brand/browse/tech.svg",
    sort_order: 3,
  },
  {
    rail: "interest",
    label: "Gospel & worship",
    hint: "Faith nights",
    href: "/events/c/gospel",
    image: "/brand/browse/gospel.svg",
    sort_order: 4,
  },
  {
    rail: "interest",
    label: "Campus events",
    hint: "Student energy",
    href: "/events/c/campus",
    image: "/brand/browse/campus.svg",
    sort_order: 5,
  },
  {
    rail: "interest",
    label: "Food & lifestyle",
    hint: "Tastings · pop-ups",
    href: "/events/c/food-drink",
    image: "/brand/browse/food-drink.svg",
    sort_order: 6,
  },
  {
    rail: "interest",
    label: "Sports & culture",
    hint: "Games · galleries",
    href: "/events/c/arts-culture",
    image: "/brand/browse/arts-culture.svg",
    sort_order: 7,
  },
  {
    rail: "city",
    label: "Lagos",
    hint: "Island · mainland",
    href: "/events/city/lagos",
    image: "/brand/browse/city-lagos.svg",
    sort_order: 0,
  },
  {
    rail: "city",
    label: "Lekki",
    hint: "Peninsula nights",
    href: "/events/area/lekki",
    image: "/brand/browse/city-lagos.svg",
    sort_order: 1,
  },
  {
    rail: "city",
    label: "Victoria Island",
    hint: "Island energy",
    href: "/events/area/victoria-island",
    image: "/brand/browse/city-lagos.svg",
    sort_order: 2,
  },
  {
    rail: "city",
    label: "Ikeja",
    hint: "Mainland pulse",
    href: "/events/area/ikeja",
    image: "/brand/browse/city-lagos.svg",
    sort_order: 3,
  },
  {
    rail: "city",
    label: "Yaba",
    hint: "Tech · campus",
    href: "/events/area/yaba",
    image: "/brand/browse/city-lagos.svg",
    sort_order: 4,
  },
  {
    rail: "city",
    label: "Ibadan",
    hint: "Ancient city pulse",
    href: "/events/city/ibadan",
    image: "/brand/browse/city-ibadan.svg",
    sort_order: 5,
  },
  {
    rail: "city",
    label: "Abuja",
    hint: "Capital nights",
    href: "/events/city/abuja",
    image: "/brand/browse/city-abuja.svg",
    sort_order: 6,
  },
  {
    rail: "city",
    label: "Akure",
    hint: "Ondo energy",
    href: "/events/city/akure",
    image: "/brand/browse/city-akure.svg",
    sort_order: 7,
  },
  {
    rail: "price",
    label: "Free",
    hint: "No ticket cost",
    href: "/events/free",
    image: "/brand/browse/price-free.svg",
    sort_order: 0,
  },
  {
    rail: "price",
    label: "Under ₦5k",
    hint: "Easy entry",
    href: "/events/under/5000",
    image: "/brand/browse/price-5k.svg",
    sort_order: 1,
  },
  {
    rail: "price",
    label: "₦5k–₦20k",
    hint: "Mid-range nights",
    href: "/events/under/20000",
    image: "/brand/browse/price-10k.svg",
    sort_order: 2,
  },
  {
    rail: "price",
    label: "VIP",
    hint: "Tables & tiers",
    href: "/events/vip",
    image: "/brand/browse/price-vip.svg",
    sort_order: 3,
  },
  {
    rail: "price",
    label: "Table packages",
    hint: "Book the room",
    href: "/events/vip",
    image: "/brand/browse/price-vip.svg",
    sort_order: 4,
  },
  {
    rail: "price",
    label: "Premium experiences",
    hint: "Higher ticket nights",
    href: "/events/under/25000",
    image: "/brand/browse/price-25k.svg",
    sort_order: 5,
  },
  {
    rail: "when",
    label: "This weekend",
    hint: "Fri–Sun picks",
    href: "/events/this-weekend",
    image: "/brand/browse/when-weekend.svg",
    sort_order: 0,
  },
  {
    rail: "when",
    label: "In person",
    hint: "Show up live",
    href: "/events/in-person",
    image: "/brand/browse/when-person.svg",
    sort_order: 1,
  },
  {
    rail: "when",
    label: "Online",
    hint: "From anywhere",
    href: "/events/online",
    image: "/brand/browse/when-online.svg",
    sort_order: 2,
  },
  {
    rail: "when",
    label: "Hybrid",
    hint: "Both ways in",
    href: "/events/hybrid",
    image: "/brand/browse/when-hybrid.svg",
    sort_order: 3,
  },
  {
    rail: "when",
    label: "Secret location",
    hint: "Reveal after booking",
    href: "/events?secret_location=1",
    image: "/brand/browse/when-person.svg",
    sort_order: 4,
  },
  {
    rail: "when",
    label: "VIP access",
    hint: "Upgrade the night",
    href: "/events/vip",
    image: "/brand/browse/price-vip.svg",
    sort_order: 5,
  },
  {
    rail: "when",
    label: "Invite-only",
    hint: "Approval required",
    href: "/events",
    image: "/brand/browse/when-hybrid.svg",
    sort_order: 6,
  },
  {
    rail: "when",
    label: "Early bird",
    hint: "Catch deals early",
    href: "/events",
    image: "/brand/browse/when-weekend.svg",
    sort_order: 7,
  },
];
