"""Ambassador / promo constants."""

# Bump when Ambassador terms copy changes; join records this version.
AMBASSADOR_TERMS_VERSION = "2026-07-19"

# Campaign types (v1). Host-wide reserved for later.
CAMPAIGN_TYPE_EVENT_TICKETS = "event_tickets"
CAMPAIGN_TYPE_EVENT_MERCH = "event_merch"
CAMPAIGN_TYPE_HOST = "host"  # not in v1

CAMPAIGN_TYPES_V1 = frozenset(
    {CAMPAIGN_TYPE_EVENT_TICKETS, CAMPAIGN_TYPE_EVENT_MERCH}
)

CAMPAIGN_TYPE_LABELS = {
    CAMPAIGN_TYPE_EVENT_TICKETS: "Event Ambassador",
    CAMPAIGN_TYPE_EVENT_MERCH: "Event Merch Ambassador",
    CAMPAIGN_TYPE_HOST: "Host Ambassador",
}

# Referral attribution
REFERRAL_COOKIE_DAYS = 30
REFERRAL_SOURCE_EXPLICIT = "explicit"
REFERRAL_SOURCE_LINK = "link"
REFERRAL_SOURCE_COOKIE = "cookie"
REFERRAL_SOURCES = frozenset(
    {REFERRAL_SOURCE_EXPLICIT, REFERRAL_SOURCE_LINK, REFERRAL_SOURCE_COOKIE}
)

# Commission / reward rules
COMMISSION_TYPE_PERCENTAGE = "percentage"
COMMISSION_TYPE_FLAT = "flat"
COMMISSION_TYPE_REWARD_ONLY = "reward_only"
COMMISSION_TYPES_V1 = frozenset(
    {
        COMMISSION_TYPE_PERCENTAGE,
        COMMISSION_TYPE_FLAT,
        COMMISSION_TYPE_REWARD_ONLY,
    }
)

APPLIES_TO_TICKETS = "tickets"
APPLIES_TO_MERCH = "merch"
APPLIES_TO_TICKETS_AND_MERCH = "tickets_and_merch"
APPLIES_TO_V1 = frozenset(
    {APPLIES_TO_TICKETS, APPLIES_TO_MERCH, APPLIES_TO_TICKETS_AND_MERCH}
)

DEFAULT_HOLD_PERIOD_DAYS = 7
DEFAULT_COOKIE_WINDOW_DAYS = 30

# Phase-9 domain enums (target schema; v1 services still use CAMPAIGN_TYPES_V1)
DOMAIN_CAMPAIGN_TYPE_EVENT = "event"
DOMAIN_CAMPAIGN_TYPE_MERCH = "merch"
DOMAIN_CAMPAIGN_TYPE_HOST = "host"
DOMAIN_CAMPAIGN_TYPE_PLATFORM = "platform"
DOMAIN_CAMPAIGN_TYPES = frozenset(
    {
        DOMAIN_CAMPAIGN_TYPE_EVENT,
        DOMAIN_CAMPAIGN_TYPE_MERCH,
        DOMAIN_CAMPAIGN_TYPE_HOST,
        DOMAIN_CAMPAIGN_TYPE_PLATFORM,
    }
)

DOMAIN_CAMPAIGN_STATUS_DRAFT = "draft"
DOMAIN_CAMPAIGN_STATUS_ACTIVE = "active"
DOMAIN_CAMPAIGN_STATUS_PAUSED = "paused"
DOMAIN_CAMPAIGN_STATUS_ENDED = "ended"
DOMAIN_CAMPAIGN_STATUS_ARCHIVED = "archived"
DOMAIN_CAMPAIGN_STATUSES = frozenset(
    {
        DOMAIN_CAMPAIGN_STATUS_DRAFT,
        DOMAIN_CAMPAIGN_STATUS_ACTIVE,
        DOMAIN_CAMPAIGN_STATUS_PAUSED,
        DOMAIN_CAMPAIGN_STATUS_ENDED,
        DOMAIN_CAMPAIGN_STATUS_ARCHIVED,
    }
)

VISIBILITY_PUBLIC_OPEN = "public_open"
VISIBILITY_INVITE_ONLY = "invite_only"
VISIBILITY_PRIVATE = "private"
CAMPAIGN_VISIBILITIES = frozenset(
    {VISIBILITY_PUBLIC_OPEN, VISIBILITY_INVITE_ONLY, VISIBILITY_PRIVATE}
)

PROFILE_STATUS_ACTIVE = "active"
PROFILE_STATUS_SUSPENDED = "suspended"
PROFILE_STATUS_BLOCKED = "blocked"
PROFILE_STATUSES = frozenset(
    {PROFILE_STATUS_ACTIVE, PROFILE_STATUS_SUSPENDED, PROFILE_STATUS_BLOCKED}
)

PARTICIPANT_STATUS_ACTIVE = "active"
PARTICIPANT_STATUS_PAUSED = "paused"
PARTICIPANT_STATUS_REMOVED = "removed"
PARTICIPANT_STATUS_BLOCKED = "blocked"
PARTICIPANT_STATUSES = frozenset(
    {
        PARTICIPANT_STATUS_ACTIVE,
        PARTICIPANT_STATUS_PAUSED,
        PARTICIPANT_STATUS_REMOVED,
        PARTICIPANT_STATUS_BLOCKED,
    }
)

ATTRIBUTION_SOURCE_LINK = "link"
ATTRIBUTION_SOURCE_CODE = "code"
ATTRIBUTION_SOURCE_QR = "qr"
ATTRIBUTION_SOURCES = frozenset(
    {ATTRIBUTION_SOURCE_LINK, ATTRIBUTION_SOURCE_CODE, ATTRIBUTION_SOURCE_QR}
)

CONVERSION_TYPE_TICKET = "ticket"
CONVERSION_TYPE_MERCH = "merch"
CONVERSION_TYPES = frozenset({CONVERSION_TYPE_TICKET, CONVERSION_TYPE_MERCH})

CONVERSION_STATUS_PENDING = "pending"
CONVERSION_STATUS_APPROVED = "approved"
CONVERSION_STATUS_PAYABLE = "payable"
CONVERSION_STATUS_PAID = "paid"
CONVERSION_STATUS_REVERSED = "reversed"
CONVERSION_STATUS_REJECTED = "rejected"
CONVERSION_STATUSES = frozenset(
    {
        CONVERSION_STATUS_PENDING,
        CONVERSION_STATUS_APPROVED,
        CONVERSION_STATUS_PAYABLE,
        CONVERSION_STATUS_PAID,
        CONVERSION_STATUS_REVERSED,
        CONVERSION_STATUS_REJECTED,
    }
)

PAYOUT_STATUS_PENDING = "pending"
PAYOUT_STATUS_APPROVED = "approved"
PAYOUT_STATUS_PAID = "paid"
PAYOUT_STATUS_CANCELLED = "cancelled"
PAYOUT_STATUSES = frozenset(
    {
        PAYOUT_STATUS_PENDING,
        PAYOUT_STATUS_APPROVED,
        PAYOUT_STATUS_PAID,
        PAYOUT_STATUS_CANCELLED,
    }
)

# Unified referral / platform-wide programs
PROGRAM_PLATFORM_WIDE = "platform_wide"
REFERRAL_SCOPE_EVENT = "event"
REFERRAL_SCOPE_PLATFORM = "platform"
REFERRAL_OWNER_HOST = "host"
REFERRAL_OWNER_PLATFORM = "platform"
PAYER_HOST = "host"
PAYER_PLATFORM = "platform"
PRODUCT_SLICE_TICKETS = "tickets"
PRODUCT_SLICE_MERCH = "merch"
PRODUCT_SLICE_ALL = "all"
ENROLLMENT_INVITE_ONLY = "invite_only"
ENROLLMENT_APPLICATION = "application"
ENROLLMENT_MANUAL = "manual_enrollment"
SAFE_LANDING_PATHS = frozenset(
    {"/", "/events", "/shop", "/ambassadors", "/marketplace"}
)
PLATFORM_REFERRAL_COOKIE_KEY = "__platform__"
