"""Expanded default location catalog for taxonomy seeding.

Generated/maintained for Event Studio country → state → city → area cascades.
Nigeria has full states + major cities/areas; other countries include a usable
Nationwide → capital cascade (or richer data for key markets).
"""

from __future__ import annotations

# (kind, name, slug, parent_slug|None, state_code|None, country_code|None)
DEFAULT_LOCATIONS: list[tuple[str, str, str, str | None, str | None, str | None]] = [
    ('country', 'Afghanistan', 'afghanistan', None, None, 'AF'),
    ('state', 'Nationwide', 'afghanistan-nationwide', 'afghanistan', None, 'AF'),
    ('city', 'Kabul', 'kabul', 'afghanistan-nationwide', None, 'AF'),
    ('country', 'Albania', 'albania', None, None, 'AL'),
    ('state', 'Nationwide', 'albania-nationwide', 'albania', None, 'AL'),
    ('city', 'Tirana', 'tirana', 'albania-nationwide', None, 'AL'),
    ('country', 'Algeria', 'algeria', None, None, 'DZ'),
    ('state', 'Nationwide', 'algeria-nationwide', 'algeria', None, 'DZ'),
    ('city', 'Algiers', 'algiers', 'algeria-nationwide', None, 'DZ'),
    ('country', 'Andorra', 'andorra', None, None, 'AD'),
    ('state', 'Nationwide', 'andorra-nationwide', 'andorra', None, 'AD'),
    ('city', 'Andorra la Vella', 'andorra-la-vella', 'andorra-nationwide', None, 'AD'),
    ('country', 'Angola', 'angola', None, None, 'AO'),
    ('state', 'Nationwide', 'angola-nationwide', 'angola', None, 'AO'),
    ('city', 'Luanda', 'luanda', 'angola-nationwide', None, 'AO'),
    ('country', 'Antigua and Barbuda', 'antigua-and-barbuda', None, None, 'AG'),
    ('state', 'Nationwide', 'antigua-and-barbuda-nationwide', 'antigua-and-barbuda', None, 'AG'),
    ('city', "Saint John's", 'saint-johns', 'antigua-and-barbuda-nationwide', None, 'AG'),
    ('country', 'Argentina', 'argentina', None, None, 'AR'),
    ('state', 'Nationwide', 'argentina-nationwide', 'argentina', None, 'AR'),
    ('city', 'Buenos Aires', 'buenos-aires', 'argentina-nationwide', None, 'AR'),
    ('country', 'Armenia', 'armenia', None, None, 'AM'),
    ('state', 'Nationwide', 'armenia-nationwide', 'armenia', None, 'AM'),
    ('city', 'Yerevan', 'yerevan', 'armenia-nationwide', None, 'AM'),
    ('country', 'Australia', 'australia', None, None, 'AU'),
    ('state', 'Nationwide', 'australia-nationwide', 'australia', None, 'AU'),
    ('city', 'Canberra', 'canberra', 'australia-nationwide', None, 'AU'),
    ('country', 'Austria', 'austria', None, None, 'AT'),
    ('state', 'Nationwide', 'austria-nationwide', 'austria', None, 'AT'),
    ('city', 'Vienna', 'vienna', 'austria-nationwide', None, 'AT'),
    ('country', 'Azerbaijan', 'azerbaijan', None, None, 'AZ'),
    ('state', 'Nationwide', 'azerbaijan-nationwide', 'azerbaijan', None, 'AZ'),
    ('city', 'Baku', 'baku', 'azerbaijan-nationwide', None, 'AZ'),
    ('country', 'Bahamas', 'bahamas', None, None, 'BS'),
    ('state', 'Nationwide', 'bahamas-nationwide', 'bahamas', None, 'BS'),
    ('city', 'Nassau', 'nassau', 'bahamas-nationwide', None, 'BS'),
    ('country', 'Bahrain', 'bahrain', None, None, 'BH'),
    ('state', 'Nationwide', 'bahrain-nationwide', 'bahrain', None, 'BH'),
    ('city', 'Manama', 'manama', 'bahrain-nationwide', None, 'BH'),
    ('country', 'Bangladesh', 'bangladesh', None, None, 'BD'),
    ('state', 'Nationwide', 'bangladesh-nationwide', 'bangladesh', None, 'BD'),
    ('city', 'Dhaka', 'dhaka', 'bangladesh-nationwide', None, 'BD'),
    ('country', 'Barbados', 'barbados', None, None, 'BB'),
    ('state', 'Nationwide', 'barbados-nationwide', 'barbados', None, 'BB'),
    ('city', 'Bridgetown', 'bridgetown', 'barbados-nationwide', None, 'BB'),
    ('country', 'Belarus', 'belarus', None, None, 'BY'),
    ('state', 'Nationwide', 'belarus-nationwide', 'belarus', None, 'BY'),
    ('city', 'Minsk', 'minsk', 'belarus-nationwide', None, 'BY'),
    ('country', 'Belgium', 'belgium', None, None, 'BE'),
    ('state', 'Nationwide', 'belgium-nationwide', 'belgium', None, 'BE'),
    ('city', 'Brussels', 'brussels', 'belgium-nationwide', None, 'BE'),
    ('country', 'Belize', 'belize', None, None, 'BZ'),
    ('state', 'Nationwide', 'belize-nationwide', 'belize', None, 'BZ'),
    ('city', 'Belmopan', 'belmopan', 'belize-nationwide', None, 'BZ'),
    ('country', 'Benin', 'benin', None, None, 'BJ'),
    ('state', 'Nationwide', 'benin-nationwide', 'benin', None, 'BJ'),
    ('city', 'Porto-Novo', 'porto-novo', 'benin-nationwide', None, 'BJ'),
    ('country', 'Bhutan', 'bhutan', None, None, 'BT'),
    ('state', 'Nationwide', 'bhutan-nationwide', 'bhutan', None, 'BT'),
    ('city', 'Thimphu', 'thimphu', 'bhutan-nationwide', None, 'BT'),
    ('country', 'Bolivia', 'bolivia', None, None, 'BO'),
    ('state', 'Nationwide', 'bolivia-nationwide', 'bolivia', None, 'BO'),
    ('city', 'Sucre', 'sucre', 'bolivia-nationwide', None, 'BO'),
    ('country', 'Bosnia and Herzegovina', 'bosnia-and-herzegovina', None, None, 'BA'),
    ('state', 'Nationwide', 'bosnia-and-herzegovina-nationwide', 'bosnia-and-herzegovina', None, 'BA'),
    ('city', 'Sarajevo', 'sarajevo', 'bosnia-and-herzegovina-nationwide', None, 'BA'),
    ('country', 'Botswana', 'botswana', None, None, 'BW'),
    ('state', 'Nationwide', 'botswana-nationwide', 'botswana', None, 'BW'),
    ('city', 'Gaborone', 'gaborone', 'botswana-nationwide', None, 'BW'),
    ('country', 'Brazil', 'brazil', None, None, 'BR'),
    ('state', 'Nationwide', 'brazil-nationwide', 'brazil', None, 'BR'),
    ('city', 'Brasília', 'brasilia', 'brazil-nationwide', None, 'BR'),
    ('country', 'Brunei', 'brunei', None, None, 'BN'),
    ('state', 'Nationwide', 'brunei-nationwide', 'brunei', None, 'BN'),
    ('city', 'Bandar Seri Begawan', 'bandar-seri-begawan', 'brunei-nationwide', None, 'BN'),
    ('country', 'Bulgaria', 'bulgaria', None, None, 'BG'),
    ('state', 'Nationwide', 'bulgaria-nationwide', 'bulgaria', None, 'BG'),
    ('city', 'Sofia', 'sofia', 'bulgaria-nationwide', None, 'BG'),
    ('country', 'Burkina Faso', 'burkina-faso', None, None, 'BF'),
    ('state', 'Nationwide', 'burkina-faso-nationwide', 'burkina-faso', None, 'BF'),
    ('city', 'Ouagadougou', 'ouagadougou', 'burkina-faso-nationwide', None, 'BF'),
    ('country', 'Burundi', 'burundi', None, None, 'BI'),
    ('state', 'Nationwide', 'burundi-nationwide', 'burundi', None, 'BI'),
    ('city', 'Gitega', 'gitega', 'burundi-nationwide', None, 'BI'),
    ('country', 'Cabo Verde', 'cabo-verde', None, None, 'CV'),
    ('state', 'Nationwide', 'cabo-verde-nationwide', 'cabo-verde', None, 'CV'),
    ('city', 'Praia', 'praia', 'cabo-verde-nationwide', None, 'CV'),
    ('country', 'Cambodia', 'cambodia', None, None, 'KH'),
    ('state', 'Nationwide', 'cambodia-nationwide', 'cambodia', None, 'KH'),
    ('city', 'Phnom Penh', 'phnom-penh', 'cambodia-nationwide', None, 'KH'),
    ('country', 'Cameroon', 'cameroon', None, None, 'CM'),
    ('state', 'Nationwide', 'cameroon-nationwide', 'cameroon', None, 'CM'),
    ('city', 'Yaoundé', 'yaounde', 'cameroon-nationwide', None, 'CM'),
    ('country', 'Canada', 'canada', None, None, 'CA'),
    ('state', 'Nationwide', 'canada-nationwide', 'canada', None, 'CA'),
    ('city', 'Ottawa', 'ottawa', 'canada-nationwide', None, 'CA'),
    ('country', 'Central African Republic', 'central-african-republic', None, None, 'CF'),
    ('state', 'Nationwide', 'central-african-republic-nationwide', 'central-african-republic', None, 'CF'),
    ('city', 'Bangui', 'bangui', 'central-african-republic-nationwide', None, 'CF'),
    ('country', 'Chad', 'chad', None, None, 'TD'),
    ('state', 'Nationwide', 'chad-nationwide', 'chad', None, 'TD'),
    ('city', "N'Djamena", 'ndjamena', 'chad-nationwide', None, 'TD'),
    ('country', 'Chile', 'chile', None, None, 'CL'),
    ('state', 'Nationwide', 'chile-nationwide', 'chile', None, 'CL'),
    ('city', 'Santiago', 'santiago', 'chile-nationwide', None, 'CL'),
    ('country', 'China', 'china', None, None, 'CN'),
    ('state', 'Nationwide', 'china-nationwide', 'china', None, 'CN'),
    ('city', 'Beijing', 'beijing', 'china-nationwide', None, 'CN'),
    ('country', 'Colombia', 'colombia', None, None, 'CO'),
    ('state', 'Nationwide', 'colombia-nationwide', 'colombia', None, 'CO'),
    ('city', 'Bogotá', 'bogota', 'colombia-nationwide', None, 'CO'),
    ('country', 'Comoros', 'comoros', None, None, 'KM'),
    ('state', 'Nationwide', 'comoros-nationwide', 'comoros', None, 'KM'),
    ('city', 'Moroni', 'moroni', 'comoros-nationwide', None, 'KM'),
    ('country', 'Congo', 'congo', None, None, 'CG'),
    ('state', 'Nationwide', 'congo-nationwide', 'congo', None, 'CG'),
    ('city', 'Brazzaville', 'brazzaville', 'congo-nationwide', None, 'CG'),
    ('country', 'Costa Rica', 'costa-rica', None, None, 'CR'),
    ('state', 'Nationwide', 'costa-rica-nationwide', 'costa-rica', None, 'CR'),
    ('city', 'San José', 'san-jose', 'costa-rica-nationwide', None, 'CR'),
    ('country', "Côte d'Ivoire", 'cote-divoire', None, None, 'CI'),
    ('state', 'Nationwide', 'cote-divoire-nationwide', 'cote-divoire', None, 'CI'),
    ('city', 'Yamoussoukro', 'yamoussoukro', 'cote-divoire-nationwide', None, 'CI'),
    ('country', 'Croatia', 'croatia', None, None, 'HR'),
    ('state', 'Nationwide', 'croatia-nationwide', 'croatia', None, 'HR'),
    ('city', 'Zagreb', 'zagreb', 'croatia-nationwide', None, 'HR'),
    ('country', 'Cuba', 'cuba', None, None, 'CU'),
    ('state', 'Nationwide', 'cuba-nationwide', 'cuba', None, 'CU'),
    ('city', 'Havana', 'havana', 'cuba-nationwide', None, 'CU'),
    ('country', 'Cyprus', 'cyprus', None, None, 'CY'),
    ('state', 'Nationwide', 'cyprus-nationwide', 'cyprus', None, 'CY'),
    ('city', 'Nicosia', 'nicosia', 'cyprus-nationwide', None, 'CY'),
    ('country', 'Czechia', 'czechia', None, None, 'CZ'),
    ('state', 'Nationwide', 'czechia-nationwide', 'czechia', None, 'CZ'),
    ('city', 'Prague', 'prague', 'czechia-nationwide', None, 'CZ'),
    ('country', 'Democratic Republic of the Congo', 'democratic-republic-of-the-congo', None, None, 'CD'),
    ('state', 'Nationwide', 'democratic-republic-of-the-congo-nationwide', 'democratic-republic-of-the-congo', None, 'CD'),
    ('city', 'Kinshasa', 'kinshasa', 'democratic-republic-of-the-congo-nationwide', None, 'CD'),
    ('country', 'Denmark', 'denmark', None, None, 'DK'),
    ('state', 'Nationwide', 'denmark-nationwide', 'denmark', None, 'DK'),
    ('city', 'Copenhagen', 'copenhagen', 'denmark-nationwide', None, 'DK'),
    ('country', 'Djibouti', 'djibouti', None, None, 'DJ'),
    ('state', 'Nationwide', 'djibouti-nationwide', 'djibouti', None, 'DJ'),
    ('city', 'Djibouti', 'djibouti-city', 'djibouti-nationwide', None, 'DJ'),
    ('country', 'Dominica', 'dominica', None, None, 'DM'),
    ('state', 'Nationwide', 'dominica-nationwide', 'dominica', None, 'DM'),
    ('city', 'Roseau', 'roseau', 'dominica-nationwide', None, 'DM'),
    ('country', 'Dominican Republic', 'dominican-republic', None, None, 'DO'),
    ('state', 'Nationwide', 'dominican-republic-nationwide', 'dominican-republic', None, 'DO'),
    ('city', 'Santo Domingo', 'santo-domingo', 'dominican-republic-nationwide', None, 'DO'),
    ('country', 'Ecuador', 'ecuador', None, None, 'EC'),
    ('state', 'Nationwide', 'ecuador-nationwide', 'ecuador', None, 'EC'),
    ('city', 'Quito', 'quito', 'ecuador-nationwide', None, 'EC'),
    ('country', 'Egypt', 'egypt', None, None, 'EG'),
    ('state', 'Nationwide', 'egypt-nationwide', 'egypt', None, 'EG'),
    ('city', 'Cairo', 'cairo', 'egypt-nationwide', None, 'EG'),
    ('country', 'El Salvador', 'el-salvador', None, None, 'SV'),
    ('state', 'Nationwide', 'el-salvador-nationwide', 'el-salvador', None, 'SV'),
    ('city', 'San Salvador', 'san-salvador', 'el-salvador-nationwide', None, 'SV'),
    ('country', 'Equatorial Guinea', 'equatorial-guinea', None, None, 'GQ'),
    ('state', 'Nationwide', 'equatorial-guinea-nationwide', 'equatorial-guinea', None, 'GQ'),
    ('city', 'Malabo', 'malabo', 'equatorial-guinea-nationwide', None, 'GQ'),
    ('country', 'Eritrea', 'eritrea', None, None, 'ER'),
    ('state', 'Nationwide', 'eritrea-nationwide', 'eritrea', None, 'ER'),
    ('city', 'Asmara', 'asmara', 'eritrea-nationwide', None, 'ER'),
    ('country', 'Estonia', 'estonia', None, None, 'EE'),
    ('state', 'Nationwide', 'estonia-nationwide', 'estonia', None, 'EE'),
    ('city', 'Tallinn', 'tallinn', 'estonia-nationwide', None, 'EE'),
    ('country', 'Eswatini', 'eswatini', None, None, 'SZ'),
    ('state', 'Nationwide', 'eswatini-nationwide', 'eswatini', None, 'SZ'),
    ('city', 'Mbabane', 'mbabane', 'eswatini-nationwide', None, 'SZ'),
    ('country', 'Ethiopia', 'ethiopia', None, None, 'ET'),
    ('state', 'Nationwide', 'ethiopia-nationwide', 'ethiopia', None, 'ET'),
    ('city', 'Addis Ababa', 'addis-ababa', 'ethiopia-nationwide', None, 'ET'),
    ('country', 'Fiji', 'fiji', None, None, 'FJ'),
    ('state', 'Nationwide', 'fiji-nationwide', 'fiji', None, 'FJ'),
    ('city', 'Suva', 'suva', 'fiji-nationwide', None, 'FJ'),
    ('country', 'Finland', 'finland', None, None, 'FI'),
    ('state', 'Nationwide', 'finland-nationwide', 'finland', None, 'FI'),
    ('city', 'Helsinki', 'helsinki', 'finland-nationwide', None, 'FI'),
    ('country', 'France', 'france', None, None, 'FR'),
    ('state', 'Nationwide', 'france-nationwide', 'france', None, 'FR'),
    ('city', 'Paris', 'paris', 'france-nationwide', None, 'FR'),
    ('country', 'Gabon', 'gabon', None, None, 'GA'),
    ('state', 'Nationwide', 'gabon-nationwide', 'gabon', None, 'GA'),
    ('city', 'Libreville', 'libreville', 'gabon-nationwide', None, 'GA'),
    ('country', 'Gambia', 'gambia', None, None, 'GM'),
    ('state', 'Nationwide', 'gambia-nationwide', 'gambia', None, 'GM'),
    ('city', 'Banjul', 'banjul', 'gambia-nationwide', None, 'GM'),
    ('country', 'Georgia', 'georgia', None, None, 'GE'),
    ('state', 'Nationwide', 'georgia-nationwide', 'georgia', None, 'GE'),
    ('city', 'Tbilisi', 'tbilisi', 'georgia-nationwide', None, 'GE'),
    ('country', 'Germany', 'germany', None, None, 'DE'),
    ('state', 'Nationwide', 'germany-nationwide', 'germany', None, 'DE'),
    ('city', 'Berlin', 'berlin', 'germany-nationwide', None, 'DE'),
    ('country', 'Ghana', 'ghana', None, None, 'GH'),
    ('state', 'Greater Accra', 'greater-accra', 'ghana', 'GA', 'GH'),
    ('state', 'Ashanti', 'ashanti', 'ghana', 'AH', 'GH'),
    ('city', 'Accra', 'accra', 'greater-accra', 'GA', 'GH'),
    ('city', 'Kumasi', 'kumasi', 'ashanti', 'AH', 'GH'),
    ('area', 'Osu', 'osu', 'accra', 'GA', 'GH'),
    ('area', 'East Legon', 'east-legon', 'accra', 'GA', 'GH'),
    ('area', 'Airport Residential', 'airport-residential', 'accra', 'GA', 'GH'),
    ('area', 'Labone', 'labone', 'accra', 'GA', 'GH'),
    ('country', 'Greece', 'greece', None, None, 'GR'),
    ('state', 'Nationwide', 'greece-nationwide', 'greece', None, 'GR'),
    ('city', 'Athens', 'athens', 'greece-nationwide', None, 'GR'),
    ('country', 'Grenada', 'grenada', None, None, 'GD'),
    ('state', 'Nationwide', 'grenada-nationwide', 'grenada', None, 'GD'),
    ('city', "Saint George's", 'saint-georges', 'grenada-nationwide', None, 'GD'),
    ('country', 'Guatemala', 'guatemala', None, None, 'GT'),
    ('state', 'Nationwide', 'guatemala-nationwide', 'guatemala', None, 'GT'),
    ('city', 'Guatemala City', 'guatemala-city', 'guatemala-nationwide', None, 'GT'),
    ('country', 'Guinea', 'guinea', None, None, 'GN'),
    ('state', 'Nationwide', 'guinea-nationwide', 'guinea', None, 'GN'),
    ('city', 'Conakry', 'conakry', 'guinea-nationwide', None, 'GN'),
    ('country', 'Guinea-Bissau', 'guinea-bissau', None, None, 'GW'),
    ('state', 'Nationwide', 'guinea-bissau-nationwide', 'guinea-bissau', None, 'GW'),
    ('city', 'Bissau', 'bissau', 'guinea-bissau-nationwide', None, 'GW'),
    ('country', 'Guyana', 'guyana', None, None, 'GY'),
    ('state', 'Nationwide', 'guyana-nationwide', 'guyana', None, 'GY'),
    ('city', 'Georgetown', 'georgetown', 'guyana-nationwide', None, 'GY'),
    ('country', 'Haiti', 'haiti', None, None, 'HT'),
    ('state', 'Nationwide', 'haiti-nationwide', 'haiti', None, 'HT'),
    ('city', 'Port-au-Prince', 'port-au-prince', 'haiti-nationwide', None, 'HT'),
    ('country', 'Honduras', 'honduras', None, None, 'HN'),
    ('state', 'Nationwide', 'honduras-nationwide', 'honduras', None, 'HN'),
    ('city', 'Tegucigalpa', 'tegucigalpa', 'honduras-nationwide', None, 'HN'),
    ('country', 'Hungary', 'hungary', None, None, 'HU'),
    ('state', 'Nationwide', 'hungary-nationwide', 'hungary', None, 'HU'),
    ('city', 'Budapest', 'budapest', 'hungary-nationwide', None, 'HU'),
    ('country', 'Iceland', 'iceland', None, None, 'IS'),
    ('state', 'Nationwide', 'iceland-nationwide', 'iceland', None, 'IS'),
    ('city', 'Reykjavik', 'reykjavik', 'iceland-nationwide', None, 'IS'),
    ('country', 'India', 'india', None, None, 'IN'),
    ('state', 'Nationwide', 'india-nationwide', 'india', None, 'IN'),
    ('city', 'New Delhi', 'new-delhi', 'india-nationwide', None, 'IN'),
    ('country', 'Indonesia', 'indonesia', None, None, 'ID'),
    ('state', 'Nationwide', 'indonesia-nationwide', 'indonesia', None, 'ID'),
    ('city', 'Jakarta', 'jakarta', 'indonesia-nationwide', None, 'ID'),
    ('country', 'Iran', 'iran', None, None, 'IR'),
    ('state', 'Nationwide', 'iran-nationwide', 'iran', None, 'IR'),
    ('city', 'Tehran', 'tehran', 'iran-nationwide', None, 'IR'),
    ('country', 'Iraq', 'iraq', None, None, 'IQ'),
    ('state', 'Nationwide', 'iraq-nationwide', 'iraq', None, 'IQ'),
    ('city', 'Baghdad', 'baghdad', 'iraq-nationwide', None, 'IQ'),
    ('country', 'Ireland', 'ireland', None, None, 'IE'),
    ('state', 'Nationwide', 'ireland-nationwide', 'ireland', None, 'IE'),
    ('city', 'Dublin', 'dublin', 'ireland-nationwide', None, 'IE'),
    ('country', 'Israel', 'israel', None, None, 'IL'),
    ('state', 'Nationwide', 'israel-nationwide', 'israel', None, 'IL'),
    ('city', 'Jerusalem', 'jerusalem', 'israel-nationwide', None, 'IL'),
    ('country', 'Italy', 'italy', None, None, 'IT'),
    ('state', 'Nationwide', 'italy-nationwide', 'italy', None, 'IT'),
    ('city', 'Rome', 'rome', 'italy-nationwide', None, 'IT'),
    ('country', 'Jamaica', 'jamaica', None, None, 'JM'),
    ('state', 'Nationwide', 'jamaica-nationwide', 'jamaica', None, 'JM'),
    ('city', 'Kingston', 'kingston', 'jamaica-nationwide', None, 'JM'),
    ('country', 'Japan', 'japan', None, None, 'JP'),
    ('state', 'Nationwide', 'japan-nationwide', 'japan', None, 'JP'),
    ('city', 'Tokyo', 'tokyo', 'japan-nationwide', None, 'JP'),
    ('country', 'Jordan', 'jordan', None, None, 'JO'),
    ('state', 'Nationwide', 'jordan-nationwide', 'jordan', None, 'JO'),
    ('city', 'Amman', 'amman', 'jordan-nationwide', None, 'JO'),
    ('country', 'Kazakhstan', 'kazakhstan', None, None, 'KZ'),
    ('state', 'Nationwide', 'kazakhstan-nationwide', 'kazakhstan', None, 'KZ'),
    ('city', 'Astana', 'astana', 'kazakhstan-nationwide', None, 'KZ'),
    ('country', 'Kenya', 'kenya', None, None, 'KE'),
    ('state', 'Nairobi County', 'nairobi-county', 'kenya', 'NR', 'KE'),
    ('state', 'Mombasa County', 'mombasa-county', 'kenya', 'MB', 'KE'),
    ('city', 'Nairobi', 'nairobi', 'nairobi-county', 'NR', 'KE'),
    ('city', 'Mombasa', 'mombasa', 'mombasa-county', 'MB', 'KE'),
    ('area', 'Westlands', 'westlands', 'nairobi', 'NR', 'KE'),
    ('area', 'Kilimani', 'kilimani', 'nairobi', 'NR', 'KE'),
    ('area', 'Karen', 'karen', 'nairobi', 'NR', 'KE'),
    ('country', 'Kiribati', 'kiribati', None, None, 'KI'),
    ('state', 'Nationwide', 'kiribati-nationwide', 'kiribati', None, 'KI'),
    ('city', 'Tarawa', 'tarawa', 'kiribati-nationwide', None, 'KI'),
    ('country', 'Kuwait', 'kuwait', None, None, 'KW'),
    ('state', 'Nationwide', 'kuwait-nationwide', 'kuwait', None, 'KW'),
    ('city', 'Kuwait City', 'kuwait-city', 'kuwait-nationwide', None, 'KW'),
    ('country', 'Kyrgyzstan', 'kyrgyzstan', None, None, 'KG'),
    ('state', 'Nationwide', 'kyrgyzstan-nationwide', 'kyrgyzstan', None, 'KG'),
    ('city', 'Bishkek', 'bishkek', 'kyrgyzstan-nationwide', None, 'KG'),
    ('country', 'Laos', 'laos', None, None, 'LA'),
    ('state', 'Nationwide', 'laos-nationwide', 'laos', None, 'LA'),
    ('city', 'Vientiane', 'vientiane', 'laos-nationwide', None, 'LA'),
    ('country', 'Latvia', 'latvia', None, None, 'LV'),
    ('state', 'Nationwide', 'latvia-nationwide', 'latvia', None, 'LV'),
    ('city', 'Riga', 'riga', 'latvia-nationwide', None, 'LV'),
    ('country', 'Lebanon', 'lebanon', None, None, 'LB'),
    ('state', 'Nationwide', 'lebanon-nationwide', 'lebanon', None, 'LB'),
    ('city', 'Beirut', 'beirut', 'lebanon-nationwide', None, 'LB'),
    ('country', 'Lesotho', 'lesotho', None, None, 'LS'),
    ('state', 'Nationwide', 'lesotho-nationwide', 'lesotho', None, 'LS'),
    ('city', 'Maseru', 'maseru', 'lesotho-nationwide', None, 'LS'),
    ('country', 'Liberia', 'liberia', None, None, 'LR'),
    ('state', 'Nationwide', 'liberia-nationwide', 'liberia', None, 'LR'),
    ('city', 'Monrovia', 'monrovia', 'liberia-nationwide', None, 'LR'),
    ('country', 'Libya', 'libya', None, None, 'LY'),
    ('state', 'Nationwide', 'libya-nationwide', 'libya', None, 'LY'),
    ('city', 'Tripoli', 'tripoli', 'libya-nationwide', None, 'LY'),
    ('country', 'Liechtenstein', 'liechtenstein', None, None, 'LI'),
    ('state', 'Nationwide', 'liechtenstein-nationwide', 'liechtenstein', None, 'LI'),
    ('city', 'Vaduz', 'vaduz', 'liechtenstein-nationwide', None, 'LI'),
    ('country', 'Lithuania', 'lithuania', None, None, 'LT'),
    ('state', 'Nationwide', 'lithuania-nationwide', 'lithuania', None, 'LT'),
    ('city', 'Vilnius', 'vilnius', 'lithuania-nationwide', None, 'LT'),
    ('country', 'Luxembourg', 'luxembourg', None, None, 'LU'),
    ('state', 'Nationwide', 'luxembourg-nationwide', 'luxembourg', None, 'LU'),
    ('city', 'Luxembourg', 'luxembourg-city', 'luxembourg-nationwide', None, 'LU'),
    ('country', 'Madagascar', 'madagascar', None, None, 'MG'),
    ('state', 'Nationwide', 'madagascar-nationwide', 'madagascar', None, 'MG'),
    ('city', 'Antananarivo', 'antananarivo', 'madagascar-nationwide', None, 'MG'),
    ('country', 'Malawi', 'malawi', None, None, 'MW'),
    ('state', 'Nationwide', 'malawi-nationwide', 'malawi', None, 'MW'),
    ('city', 'Lilongwe', 'lilongwe', 'malawi-nationwide', None, 'MW'),
    ('country', 'Malaysia', 'malaysia', None, None, 'MY'),
    ('state', 'Nationwide', 'malaysia-nationwide', 'malaysia', None, 'MY'),
    ('city', 'Kuala Lumpur', 'kuala-lumpur', 'malaysia-nationwide', None, 'MY'),
    ('country', 'Maldives', 'maldives', None, None, 'MV'),
    ('state', 'Nationwide', 'maldives-nationwide', 'maldives', None, 'MV'),
    ('city', 'Malé', 'male', 'maldives-nationwide', None, 'MV'),
    ('country', 'Mali', 'mali', None, None, 'ML'),
    ('state', 'Nationwide', 'mali-nationwide', 'mali', None, 'ML'),
    ('city', 'Bamako', 'bamako', 'mali-nationwide', None, 'ML'),
    ('country', 'Malta', 'malta', None, None, 'MT'),
    ('state', 'Nationwide', 'malta-nationwide', 'malta', None, 'MT'),
    ('city', 'Valletta', 'valletta', 'malta-nationwide', None, 'MT'),
    ('country', 'Marshall Islands', 'marshall-islands', None, None, 'MH'),
    ('state', 'Nationwide', 'marshall-islands-nationwide', 'marshall-islands', None, 'MH'),
    ('city', 'Majuro', 'majuro', 'marshall-islands-nationwide', None, 'MH'),
    ('country', 'Mauritania', 'mauritania', None, None, 'MR'),
    ('state', 'Nationwide', 'mauritania-nationwide', 'mauritania', None, 'MR'),
    ('city', 'Nouakchott', 'nouakchott', 'mauritania-nationwide', None, 'MR'),
    ('country', 'Mauritius', 'mauritius', None, None, 'MU'),
    ('state', 'Nationwide', 'mauritius-nationwide', 'mauritius', None, 'MU'),
    ('city', 'Port Louis', 'port-louis', 'mauritius-nationwide', None, 'MU'),
    ('country', 'Mexico', 'mexico', None, None, 'MX'),
    ('state', 'Nationwide', 'mexico-nationwide', 'mexico', None, 'MX'),
    ('city', 'Mexico City', 'mexico-city', 'mexico-nationwide', None, 'MX'),
    ('country', 'Micronesia', 'micronesia', None, None, 'FM'),
    ('state', 'Nationwide', 'micronesia-nationwide', 'micronesia', None, 'FM'),
    ('city', 'Palikir', 'palikir', 'micronesia-nationwide', None, 'FM'),
    ('country', 'Moldova', 'moldova', None, None, 'MD'),
    ('state', 'Nationwide', 'moldova-nationwide', 'moldova', None, 'MD'),
    ('city', 'Chișinău', 'chi-in-u', 'moldova-nationwide', None, 'MD'),
    ('country', 'Monaco', 'monaco', None, None, 'MC'),
    ('state', 'Nationwide', 'monaco-nationwide', 'monaco', None, 'MC'),
    ('city', 'Monaco', 'monaco-city', 'monaco-nationwide', None, 'MC'),
    ('country', 'Mongolia', 'mongolia', None, None, 'MN'),
    ('state', 'Nationwide', 'mongolia-nationwide', 'mongolia', None, 'MN'),
    ('city', 'Ulaanbaatar', 'ulaanbaatar', 'mongolia-nationwide', None, 'MN'),
    ('country', 'Montenegro', 'montenegro', None, None, 'ME'),
    ('state', 'Nationwide', 'montenegro-nationwide', 'montenegro', None, 'ME'),
    ('city', 'Podgorica', 'podgorica', 'montenegro-nationwide', None, 'ME'),
    ('country', 'Morocco', 'morocco', None, None, 'MA'),
    ('state', 'Nationwide', 'morocco-nationwide', 'morocco', None, 'MA'),
    ('city', 'Rabat', 'rabat', 'morocco-nationwide', None, 'MA'),
    ('country', 'Mozambique', 'mozambique', None, None, 'MZ'),
    ('state', 'Nationwide', 'mozambique-nationwide', 'mozambique', None, 'MZ'),
    ('city', 'Maputo', 'maputo', 'mozambique-nationwide', None, 'MZ'),
    ('country', 'Myanmar', 'myanmar', None, None, 'MM'),
    ('state', 'Nationwide', 'myanmar-nationwide', 'myanmar', None, 'MM'),
    ('city', 'Naypyidaw', 'naypyidaw', 'myanmar-nationwide', None, 'MM'),
    ('country', 'Namibia', 'namibia', None, None, 'NA'),
    ('state', 'Nationwide', 'namibia-nationwide', 'namibia', None, 'NA'),
    ('city', 'Windhoek', 'windhoek', 'namibia-nationwide', None, 'NA'),
    ('country', 'Nauru', 'nauru', None, None, 'NR'),
    ('state', 'Nationwide', 'nauru-nationwide', 'nauru', None, 'NR'),
    ('city', 'Yaren', 'yaren', 'nauru-nationwide', None, 'NR'),
    ('country', 'Nepal', 'nepal', None, None, 'NP'),
    ('state', 'Nationwide', 'nepal-nationwide', 'nepal', None, 'NP'),
    ('city', 'Kathmandu', 'kathmandu', 'nepal-nationwide', None, 'NP'),
    ('country', 'Netherlands', 'netherlands', None, None, 'NL'),
    ('state', 'Nationwide', 'netherlands-nationwide', 'netherlands', None, 'NL'),
    ('city', 'Amsterdam', 'amsterdam', 'netherlands-nationwide', None, 'NL'),
    ('country', 'New Zealand', 'new-zealand', None, None, 'NZ'),
    ('state', 'Nationwide', 'new-zealand-nationwide', 'new-zealand', None, 'NZ'),
    ('city', 'Wellington', 'wellington', 'new-zealand-nationwide', None, 'NZ'),
    ('country', 'Nicaragua', 'nicaragua', None, None, 'NI'),
    ('state', 'Nationwide', 'nicaragua-nationwide', 'nicaragua', None, 'NI'),
    ('city', 'Managua', 'managua', 'nicaragua-nationwide', None, 'NI'),
    ('country', 'Niger', 'niger', None, None, 'NE'),
    ('state', 'Nationwide', 'niger-nationwide', 'niger', None, 'NE'),
    ('city', 'Niamey', 'niamey', 'niger-nationwide', None, 'NE'),
    ('country', 'Nigeria', 'nigeria', None, None, 'NG'),
    ('country', 'North Korea', 'north-korea', None, None, 'KP'),
    ('state', 'Nationwide', 'north-korea-nationwide', 'north-korea', None, 'KP'),
    ('city', 'Pyongyang', 'pyongyang', 'north-korea-nationwide', None, 'KP'),
    ('country', 'North Macedonia', 'north-macedonia', None, None, 'MK'),
    ('state', 'Nationwide', 'north-macedonia-nationwide', 'north-macedonia', None, 'MK'),
    ('city', 'Skopje', 'skopje', 'north-macedonia-nationwide', None, 'MK'),
    ('country', 'Norway', 'norway', None, None, 'NO'),
    ('state', 'Nationwide', 'norway-nationwide', 'norway', None, 'NO'),
    ('city', 'Oslo', 'oslo', 'norway-nationwide', None, 'NO'),
    ('country', 'Oman', 'oman', None, None, 'OM'),
    ('state', 'Nationwide', 'oman-nationwide', 'oman', None, 'OM'),
    ('city', 'Muscat', 'muscat', 'oman-nationwide', None, 'OM'),
    ('country', 'Pakistan', 'pakistan', None, None, 'PK'),
    ('state', 'Nationwide', 'pakistan-nationwide', 'pakistan', None, 'PK'),
    ('city', 'Islamabad', 'islamabad', 'pakistan-nationwide', None, 'PK'),
    ('country', 'Palau', 'palau', None, None, 'PW'),
    ('state', 'Nationwide', 'palau-nationwide', 'palau', None, 'PW'),
    ('city', 'Ngerulmud', 'ngerulmud', 'palau-nationwide', None, 'PW'),
    ('country', 'Palestine', 'palestine', None, None, 'PS'),
    ('state', 'Nationwide', 'palestine-nationwide', 'palestine', None, 'PS'),
    ('city', 'Ramallah', 'ramallah', 'palestine-nationwide', None, 'PS'),
    ('country', 'Panama', 'panama', None, None, 'PA'),
    ('state', 'Nationwide', 'panama-nationwide', 'panama', None, 'PA'),
    ('city', 'Panama City', 'panama-city', 'panama-nationwide', None, 'PA'),
    ('country', 'Papua New Guinea', 'papua-new-guinea', None, None, 'PG'),
    ('state', 'Nationwide', 'papua-new-guinea-nationwide', 'papua-new-guinea', None, 'PG'),
    ('city', 'Port Moresby', 'port-moresby', 'papua-new-guinea-nationwide', None, 'PG'),
    ('country', 'Paraguay', 'paraguay', None, None, 'PY'),
    ('state', 'Nationwide', 'paraguay-nationwide', 'paraguay', None, 'PY'),
    ('city', 'Asunción', 'asunci-n', 'paraguay-nationwide', None, 'PY'),
    ('country', 'Peru', 'peru', None, None, 'PE'),
    ('state', 'Nationwide', 'peru-nationwide', 'peru', None, 'PE'),
    ('city', 'Lima', 'lima', 'peru-nationwide', None, 'PE'),
    ('country', 'Philippines', 'philippines', None, None, 'PH'),
    ('state', 'Nationwide', 'philippines-nationwide', 'philippines', None, 'PH'),
    ('city', 'Manila', 'manila', 'philippines-nationwide', None, 'PH'),
    ('country', 'Poland', 'poland', None, None, 'PL'),
    ('state', 'Nationwide', 'poland-nationwide', 'poland', None, 'PL'),
    ('city', 'Warsaw', 'warsaw', 'poland-nationwide', None, 'PL'),
    ('country', 'Portugal', 'portugal', None, None, 'PT'),
    ('state', 'Nationwide', 'portugal-nationwide', 'portugal', None, 'PT'),
    ('city', 'Lisbon', 'lisbon', 'portugal-nationwide', None, 'PT'),
    ('country', 'Qatar', 'qatar', None, None, 'QA'),
    ('state', 'Nationwide', 'qatar-nationwide', 'qatar', None, 'QA'),
    ('city', 'Doha', 'doha', 'qatar-nationwide', None, 'QA'),
    ('country', 'Romania', 'romania', None, None, 'RO'),
    ('state', 'Nationwide', 'romania-nationwide', 'romania', None, 'RO'),
    ('city', 'Bucharest', 'bucharest', 'romania-nationwide', None, 'RO'),
    ('country', 'Russia', 'russia', None, None, 'RU'),
    ('state', 'Nationwide', 'russia-nationwide', 'russia', None, 'RU'),
    ('city', 'Moscow', 'moscow', 'russia-nationwide', None, 'RU'),
    ('country', 'Rwanda', 'rwanda', None, None, 'RW'),
    ('state', 'Nationwide', 'rwanda-nationwide', 'rwanda', None, 'RW'),
    ('city', 'Kigali', 'kigali', 'rwanda-nationwide', None, 'RW'),
    ('country', 'Saint Kitts and Nevis', 'saint-kitts-and-nevis', None, None, 'KN'),
    ('state', 'Nationwide', 'saint-kitts-and-nevis-nationwide', 'saint-kitts-and-nevis', None, 'KN'),
    ('city', 'Basseterre', 'basseterre', 'saint-kitts-and-nevis-nationwide', None, 'KN'),
    ('country', 'Saint Lucia', 'saint-lucia', None, None, 'LC'),
    ('state', 'Nationwide', 'saint-lucia-nationwide', 'saint-lucia', None, 'LC'),
    ('city', 'Castries', 'castries', 'saint-lucia-nationwide', None, 'LC'),
    ('country', 'Saint Vincent and the Grenadines', 'saint-vincent-and-the-grenadines', None, None, 'VC'),
    ('state', 'Nationwide', 'saint-vincent-and-the-grenadines-nationwide', 'saint-vincent-and-the-grenadines', None, 'VC'),
    ('city', 'Kingstown', 'kingstown', 'saint-vincent-and-the-grenadines-nationwide', None, 'VC'),
    ('country', 'Samoa', 'samoa', None, None, 'WS'),
    ('state', 'Nationwide', 'samoa-nationwide', 'samoa', None, 'WS'),
    ('city', 'Apia', 'apia', 'samoa-nationwide', None, 'WS'),
    ('country', 'San Marino', 'san-marino', None, None, 'SM'),
    ('state', 'Nationwide', 'san-marino-nationwide', 'san-marino', None, 'SM'),
    ('city', 'San Marino', 'san-marino-city', 'san-marino-nationwide', None, 'SM'),
    ('country', 'Sao Tome and Principe', 'sao-tome-and-principe', None, None, 'ST'),
    ('state', 'Nationwide', 'sao-tome-and-principe-nationwide', 'sao-tome-and-principe', None, 'ST'),
    ('city', 'São Tomé', 's-o-tome', 'sao-tome-and-principe-nationwide', None, 'ST'),
    ('country', 'Saudi Arabia', 'saudi-arabia', None, None, 'SA'),
    ('state', 'Nationwide', 'saudi-arabia-nationwide', 'saudi-arabia', None, 'SA'),
    ('city', 'Riyadh', 'riyadh', 'saudi-arabia-nationwide', None, 'SA'),
    ('country', 'Senegal', 'senegal', None, None, 'SN'),
    ('state', 'Nationwide', 'senegal-nationwide', 'senegal', None, 'SN'),
    ('city', 'Dakar', 'dakar', 'senegal-nationwide', None, 'SN'),
    ('country', 'Serbia', 'serbia', None, None, 'RS'),
    ('state', 'Nationwide', 'serbia-nationwide', 'serbia', None, 'RS'),
    ('city', 'Belgrade', 'belgrade', 'serbia-nationwide', None, 'RS'),
    ('country', 'Seychelles', 'seychelles', None, None, 'SC'),
    ('state', 'Nationwide', 'seychelles-nationwide', 'seychelles', None, 'SC'),
    ('city', 'Victoria', 'victoria', 'seychelles-nationwide', None, 'SC'),
    ('country', 'Sierra Leone', 'sierra-leone', None, None, 'SL'),
    ('state', 'Nationwide', 'sierra-leone-nationwide', 'sierra-leone', None, 'SL'),
    ('city', 'Freetown', 'freetown', 'sierra-leone-nationwide', None, 'SL'),
    ('country', 'Singapore', 'singapore', None, None, 'SG'),
    ('state', 'Nationwide', 'singapore-nationwide', 'singapore', None, 'SG'),
    ('city', 'Singapore', 'singapore-city', 'singapore-nationwide', None, 'SG'),
    ('country', 'Slovakia', 'slovakia', None, None, 'SK'),
    ('state', 'Nationwide', 'slovakia-nationwide', 'slovakia', None, 'SK'),
    ('city', 'Bratislava', 'bratislava', 'slovakia-nationwide', None, 'SK'),
    ('country', 'Slovenia', 'slovenia', None, None, 'SI'),
    ('state', 'Nationwide', 'slovenia-nationwide', 'slovenia', None, 'SI'),
    ('city', 'Ljubljana', 'ljubljana', 'slovenia-nationwide', None, 'SI'),
    ('country', 'Solomon Islands', 'solomon-islands', None, None, 'SB'),
    ('state', 'Nationwide', 'solomon-islands-nationwide', 'solomon-islands', None, 'SB'),
    ('city', 'Honiara', 'honiara', 'solomon-islands-nationwide', None, 'SB'),
    ('country', 'Somalia', 'somalia', None, None, 'SO'),
    ('state', 'Nationwide', 'somalia-nationwide', 'somalia', None, 'SO'),
    ('city', 'Mogadishu', 'mogadishu', 'somalia-nationwide', None, 'SO'),
    ('country', 'South Africa', 'south-africa', None, None, 'ZA'),
    ('state', 'Gauteng', 'gauteng', 'south-africa', 'GP', 'ZA'),
    ('state', 'Western Cape', 'western-cape', 'south-africa', 'WC', 'ZA'),
    ('city', 'Johannesburg', 'johannesburg', 'gauteng', 'GP', 'ZA'),
    ('city', 'Pretoria', 'pretoria', 'gauteng', 'GP', 'ZA'),
    ('city', 'Cape Town', 'cape-town', 'western-cape', 'WC', 'ZA'),
    ('area', 'Sandton', 'sandton', 'johannesburg', 'GP', 'ZA'),
    ('area', 'Rosebank', 'rosebank-jhb', 'johannesburg', 'GP', 'ZA'),
    ('country', 'South Korea', 'south-korea', None, None, 'KR'),
    ('state', 'Nationwide', 'south-korea-nationwide', 'south-korea', None, 'KR'),
    ('city', 'Seoul', 'seoul', 'south-korea-nationwide', None, 'KR'),
    ('country', 'South Sudan', 'south-sudan', None, None, 'SS'),
    ('state', 'Nationwide', 'south-sudan-nationwide', 'south-sudan', None, 'SS'),
    ('city', 'Juba', 'juba', 'south-sudan-nationwide', None, 'SS'),
    ('country', 'Spain', 'spain', None, None, 'ES'),
    ('state', 'Nationwide', 'spain-nationwide', 'spain', None, 'ES'),
    ('city', 'Madrid', 'madrid', 'spain-nationwide', None, 'ES'),
    ('country', 'Sri Lanka', 'sri-lanka', None, None, 'LK'),
    ('state', 'Nationwide', 'sri-lanka-nationwide', 'sri-lanka', None, 'LK'),
    ('city', 'Sri Jayawardenepura Kotte', 'sri-jayawardenepura-kotte', 'sri-lanka-nationwide', None, 'LK'),
    ('country', 'Sudan', 'sudan', None, None, 'SD'),
    ('state', 'Nationwide', 'sudan-nationwide', 'sudan', None, 'SD'),
    ('city', 'Khartoum', 'khartoum', 'sudan-nationwide', None, 'SD'),
    ('country', 'Suriname', 'suriname', None, None, 'SR'),
    ('state', 'Nationwide', 'suriname-nationwide', 'suriname', None, 'SR'),
    ('city', 'Paramaribo', 'paramaribo', 'suriname-nationwide', None, 'SR'),
    ('country', 'Sweden', 'sweden', None, None, 'SE'),
    ('state', 'Nationwide', 'sweden-nationwide', 'sweden', None, 'SE'),
    ('city', 'Stockholm', 'stockholm', 'sweden-nationwide', None, 'SE'),
    ('country', 'Switzerland', 'switzerland', None, None, 'CH'),
    ('state', 'Nationwide', 'switzerland-nationwide', 'switzerland', None, 'CH'),
    ('city', 'Bern', 'bern', 'switzerland-nationwide', None, 'CH'),
    ('country', 'Syria', 'syria', None, None, 'SY'),
    ('state', 'Nationwide', 'syria-nationwide', 'syria', None, 'SY'),
    ('city', 'Damascus', 'damascus', 'syria-nationwide', None, 'SY'),
    ('country', 'Taiwan', 'taiwan', None, None, 'TW'),
    ('state', 'Nationwide', 'taiwan-nationwide', 'taiwan', None, 'TW'),
    ('city', 'Taipei', 'taipei', 'taiwan-nationwide', None, 'TW'),
    ('country', 'Tajikistan', 'tajikistan', None, None, 'TJ'),
    ('state', 'Nationwide', 'tajikistan-nationwide', 'tajikistan', None, 'TJ'),
    ('city', 'Dushanbe', 'dushanbe', 'tajikistan-nationwide', None, 'TJ'),
    ('country', 'Tanzania', 'tanzania', None, None, 'TZ'),
    ('state', 'Nationwide', 'tanzania-nationwide', 'tanzania', None, 'TZ'),
    ('city', 'Dodoma', 'dodoma', 'tanzania-nationwide', None, 'TZ'),
    ('country', 'Thailand', 'thailand', None, None, 'TH'),
    ('state', 'Nationwide', 'thailand-nationwide', 'thailand', None, 'TH'),
    ('city', 'Bangkok', 'bangkok', 'thailand-nationwide', None, 'TH'),
    ('country', 'Timor-Leste', 'timor-leste', None, None, 'TL'),
    ('state', 'Nationwide', 'timor-leste-nationwide', 'timor-leste', None, 'TL'),
    ('city', 'Dili', 'dili', 'timor-leste-nationwide', None, 'TL'),
    ('country', 'Togo', 'togo', None, None, 'TG'),
    ('state', 'Nationwide', 'togo-nationwide', 'togo', None, 'TG'),
    ('city', 'Lomé', 'lome', 'togo-nationwide', None, 'TG'),
    ('country', 'Tonga', 'tonga', None, None, 'TO'),
    ('state', 'Nationwide', 'tonga-nationwide', 'tonga', None, 'TO'),
    ('city', 'Nukuʻalofa', 'nuku-alofa', 'tonga-nationwide', None, 'TO'),
    ('country', 'Trinidad and Tobago', 'trinidad-and-tobago', None, None, 'TT'),
    ('state', 'Nationwide', 'trinidad-and-tobago-nationwide', 'trinidad-and-tobago', None, 'TT'),
    ('city', 'Port of Spain', 'port-of-spain', 'trinidad-and-tobago-nationwide', None, 'TT'),
    ('country', 'Tunisia', 'tunisia', None, None, 'TN'),
    ('state', 'Nationwide', 'tunisia-nationwide', 'tunisia', None, 'TN'),
    ('city', 'Tunis', 'tunis', 'tunisia-nationwide', None, 'TN'),
    ('country', 'Turkey', 'turkey', None, None, 'TR'),
    ('state', 'Nationwide', 'turkey-nationwide', 'turkey', None, 'TR'),
    ('city', 'Ankara', 'ankara', 'turkey-nationwide', None, 'TR'),
    ('country', 'Turkmenistan', 'turkmenistan', None, None, 'TM'),
    ('state', 'Nationwide', 'turkmenistan-nationwide', 'turkmenistan', None, 'TM'),
    ('city', 'Ashgabat', 'ashgabat', 'turkmenistan-nationwide', None, 'TM'),
    ('country', 'Tuvalu', 'tuvalu', None, None, 'TV'),
    ('state', 'Nationwide', 'tuvalu-nationwide', 'tuvalu', None, 'TV'),
    ('city', 'Funafuti', 'funafuti', 'tuvalu-nationwide', None, 'TV'),
    ('country', 'Uganda', 'uganda', None, None, 'UG'),
    ('state', 'Nationwide', 'uganda-nationwide', 'uganda', None, 'UG'),
    ('city', 'Kampala', 'kampala', 'uganda-nationwide', None, 'UG'),
    ('country', 'Ukraine', 'ukraine', None, None, 'UA'),
    ('state', 'Nationwide', 'ukraine-nationwide', 'ukraine', None, 'UA'),
    ('city', 'Kyiv', 'kyiv', 'ukraine-nationwide', None, 'UA'),
    ('country', 'United Arab Emirates', 'united-arab-emirates', None, None, 'AE'),
    ('state', 'Nationwide', 'united-arab-emirates-nationwide', 'united-arab-emirates', None, 'AE'),
    ('city', 'Abu Dhabi', 'abu-dhabi', 'united-arab-emirates-nationwide', None, 'AE'),
    ('country', 'United Kingdom', 'united-kingdom', None, None, 'GB'),
    ('state', 'England', 'england', 'united-kingdom', 'ENG', 'GB'),
    ('state', 'Scotland', 'scotland', 'united-kingdom', 'SCT', 'GB'),
    ('city', 'London', 'london', 'england', 'ENG', 'GB'),
    ('city', 'Manchester', 'manchester', 'england', 'ENG', 'GB'),
    ('city', 'Edinburgh', 'edinburgh', 'scotland', 'SCT', 'GB'),
    ('area', 'Shoreditch', 'shoreditch', 'london', 'ENG', 'GB'),
    ('area', 'Brixton', 'brixton', 'london', 'ENG', 'GB'),
    ('area', 'Canary Wharf', 'canary-wharf', 'london', 'ENG', 'GB'),
    ('country', 'United States', 'united-states', None, None, 'US'),
    ('state', 'New York', 'new-york', 'united-states', 'NY', 'US'),
    ('state', 'California', 'california', 'united-states', 'CA', 'US'),
    ('state', 'Texas', 'texas', 'united-states', 'TX', 'US'),
    ('state', 'Georgia', 'georgia-us', 'united-states', 'GA', 'US'),
    ('city', 'New York City', 'new-york-city', 'new-york', 'NY', 'US'),
    ('city', 'Los Angeles', 'los-angeles', 'california', 'CA', 'US'),
    ('city', 'Houston', 'houston', 'texas', 'TX', 'US'),
    ('city', 'Atlanta', 'atlanta', 'georgia-us', 'GA', 'US'),
    ('area', 'Brooklyn', 'brooklyn', 'new-york-city', 'NY', 'US'),
    ('area', 'Manhattan', 'manhattan', 'new-york-city', 'NY', 'US'),
    ('area', 'Queens', 'queens', 'new-york-city', 'NY', 'US'),
    ('country', 'Uruguay', 'uruguay', None, None, 'UY'),
    ('state', 'Nationwide', 'uruguay-nationwide', 'uruguay', None, 'UY'),
    ('city', 'Montevideo', 'montevideo', 'uruguay-nationwide', None, 'UY'),
    ('country', 'Uzbekistan', 'uzbekistan', None, None, 'UZ'),
    ('state', 'Nationwide', 'uzbekistan-nationwide', 'uzbekistan', None, 'UZ'),
    ('city', 'Tashkent', 'tashkent', 'uzbekistan-nationwide', None, 'UZ'),
    ('country', 'Vanuatu', 'vanuatu', None, None, 'VU'),
    ('state', 'Nationwide', 'vanuatu-nationwide', 'vanuatu', None, 'VU'),
    ('city', 'Port Vila', 'port-vila', 'vanuatu-nationwide', None, 'VU'),
    ('country', 'Vatican City', 'vatican-city', None, None, 'VA'),
    ('state', 'Nationwide', 'vatican-city-nationwide', 'vatican-city', None, 'VA'),
    ('city', 'Vatican City', 'vatican-city-city', 'vatican-city-nationwide', None, 'VA'),
    ('country', 'Venezuela', 'venezuela', None, None, 'VE'),
    ('state', 'Nationwide', 'venezuela-nationwide', 'venezuela', None, 'VE'),
    ('city', 'Caracas', 'caracas', 'venezuela-nationwide', None, 'VE'),
    ('country', 'Vietnam', 'vietnam', None, None, 'VN'),
    ('state', 'Nationwide', 'vietnam-nationwide', 'vietnam', None, 'VN'),
    ('city', 'Hanoi', 'hanoi', 'vietnam-nationwide', None, 'VN'),
    ('country', 'Yemen', 'yemen', None, None, 'YE'),
    ('state', 'Nationwide', 'yemen-nationwide', 'yemen', None, 'YE'),
    ('city', 'Sanaa', 'sanaa', 'yemen-nationwide', None, 'YE'),
    ('country', 'Zambia', 'zambia', None, None, 'ZM'),
    ('state', 'Nationwide', 'zambia-nationwide', 'zambia', None, 'ZM'),
    ('city', 'Lusaka', 'lusaka', 'zambia-nationwide', None, 'ZM'),
    ('country', 'Zimbabwe', 'zimbabwe', None, None, 'ZW'),
    ('state', 'Nationwide', 'zimbabwe-nationwide', 'zimbabwe', None, 'ZW'),
    ('city', 'Harare', 'harare', 'zimbabwe-nationwide', None, 'ZW'),
    ('state', 'Abia', 'abia', 'nigeria', 'AB', 'NG'),
    ('city', 'Umuahia', 'umuahia', 'abia', 'AB', 'NG'),
    ('state', 'Adamawa', 'adamawa', 'nigeria', 'AD', 'NG'),
    ('city', 'Yola', 'yola', 'adamawa', 'AD', 'NG'),
    ('state', 'Akwa Ibom', 'akwa-ibom', 'nigeria', 'AK', 'NG'),
    ('city', 'Uyo', 'uyo', 'akwa-ibom', 'AK', 'NG'),
    ('state', 'Anambra', 'anambra', 'nigeria', 'AN', 'NG'),
    ('city', 'Awka', 'awka', 'anambra', 'AN', 'NG'),
    ('state', 'Bauchi', 'bauchi', 'nigeria', 'BA', 'NG'),
    ('city', 'Bauchi', 'bauchi-city', 'bauchi', 'BA', 'NG'),
    ('state', 'Bayelsa', 'bayelsa', 'nigeria', 'BY', 'NG'),
    ('city', 'Yenagoa', 'yenagoa', 'bayelsa', 'BY', 'NG'),
    ('state', 'Benue', 'benue', 'nigeria', 'BE', 'NG'),
    ('city', 'Makurdi', 'makurdi', 'benue', 'BE', 'NG'),
    ('state', 'Borno', 'borno', 'nigeria', 'BO', 'NG'),
    ('city', 'Maiduguri', 'maiduguri', 'borno', 'BO', 'NG'),
    ('state', 'Cross River', 'cross-river', 'nigeria', 'CR', 'NG'),
    ('city', 'Calabar', 'calabar', 'cross-river', 'CR', 'NG'),
    ('state', 'Delta', 'delta', 'nigeria', 'DE', 'NG'),
    ('city', 'Asaba', 'asaba', 'delta', 'DE', 'NG'),
    ('state', 'Ebonyi', 'ebonyi', 'nigeria', 'EB', 'NG'),
    ('city', 'Abakaliki', 'abakaliki', 'ebonyi', 'EB', 'NG'),
    ('state', 'Edo', 'edo', 'nigeria', 'ED', 'NG'),
    ('city', 'Benin City', 'benin-city', 'edo', 'ED', 'NG'),
    ('state', 'Ekiti', 'ekiti', 'nigeria', 'EK', 'NG'),
    ('city', 'Ado-Ekiti', 'ado-ekiti', 'ekiti', 'EK', 'NG'),
    ('state', 'Enugu', 'enugu', 'nigeria', 'EN', 'NG'),
    ('city', 'Enugu', 'enugu-city', 'enugu', 'EN', 'NG'),
    ('state', 'FCT', 'fct', 'nigeria', 'FC', 'NG'),
    ('city', 'Abuja', 'abuja', 'fct', 'FC', 'NG'),
    ('state', 'Gombe', 'gombe', 'nigeria', 'GO', 'NG'),
    ('city', 'Gombe', 'gombe-city', 'gombe', 'GO', 'NG'),
    ('state', 'Imo', 'imo', 'nigeria', 'IM', 'NG'),
    ('city', 'Owerri', 'owerri', 'imo', 'IM', 'NG'),
    ('state', 'Jigawa', 'jigawa', 'nigeria', 'JI', 'NG'),
    ('city', 'Dutse', 'dutse', 'jigawa', 'JI', 'NG'),
    ('state', 'Kaduna', 'kaduna', 'nigeria', 'KD', 'NG'),
    ('city', 'Kaduna', 'kaduna-city', 'kaduna', 'KD', 'NG'),
    ('state', 'Kano', 'kano', 'nigeria', 'KN', 'NG'),
    ('city', 'Kano', 'kano-city', 'kano', 'KN', 'NG'),
    ('state', 'Katsina', 'katsina', 'nigeria', 'KT', 'NG'),
    ('city', 'Katsina', 'katsina-city', 'katsina', 'KT', 'NG'),
    ('state', 'Kebbi', 'kebbi', 'nigeria', 'KE', 'NG'),
    ('city', 'Birnin Kebbi', 'birnin-kebbi', 'kebbi', 'KE', 'NG'),
    ('state', 'Kogi', 'kogi', 'nigeria', 'KO', 'NG'),
    ('city', 'Lokoja', 'lokoja', 'kogi', 'KO', 'NG'),
    ('state', 'Kwara', 'kwara', 'nigeria', 'KW', 'NG'),
    ('city', 'Ilorin', 'ilorin', 'kwara', 'KW', 'NG'),
    ('state', 'Lagos', 'lagos', 'nigeria', 'LA', 'NG'),
    ('city', 'Lagos', 'lagos', 'lagos', 'LA', 'NG'),
    ('state', 'Nasarawa', 'nasarawa', 'nigeria', 'NA', 'NG'),
    ('city', 'Lafia', 'lafia', 'nasarawa', 'NA', 'NG'),
    ('state', 'Niger', 'niger', 'nigeria', 'NI', 'NG'),
    ('city', 'Minna', 'minna', 'niger', 'NI', 'NG'),
    ('state', 'Ogun', 'ogun', 'nigeria', 'OG', 'NG'),
    ('city', 'Abeokuta', 'abeokuta', 'ogun', 'OG', 'NG'),
    ('state', 'Ondo', 'ondo', 'nigeria', 'ON', 'NG'),
    ('city', 'Akure', 'akure', 'ondo', 'ON', 'NG'),
    ('state', 'Osun', 'osun', 'nigeria', 'OS', 'NG'),
    ('city', 'Osogbo', 'osogbo', 'osun', 'OS', 'NG'),
    ('state', 'Oyo', 'oyo', 'nigeria', 'OY', 'NG'),
    ('city', 'Ibadan', 'ibadan', 'oyo', 'OY', 'NG'),
    ('state', 'Plateau', 'plateau', 'nigeria', 'PL', 'NG'),
    ('city', 'Jos', 'jos', 'plateau', 'PL', 'NG'),
    ('state', 'Rivers', 'rivers', 'nigeria', 'RI', 'NG'),
    ('city', 'Port Harcourt', 'port-harcourt', 'rivers', 'RI', 'NG'),
    ('state', 'Sokoto', 'sokoto', 'nigeria', 'SO', 'NG'),
    ('city', 'Sokoto', 'sokoto-city', 'sokoto', 'SO', 'NG'),
    ('state', 'Taraba', 'taraba', 'nigeria', 'TA', 'NG'),
    ('city', 'Jalingo', 'jalingo', 'taraba', 'TA', 'NG'),
    ('state', 'Yobe', 'yobe', 'nigeria', 'YO', 'NG'),
    ('city', 'Damaturu', 'damaturu', 'yobe', 'YO', 'NG'),
    ('state', 'Zamfara', 'zamfara', 'nigeria', 'ZA', 'NG'),
    ('city', 'Gusau', 'gusau', 'zamfara', 'ZA', 'NG'),
    ('city', 'Ikorodu', 'ikorodu', 'lagos', 'LA', 'NG'),
    ('city', 'Epe', 'epe', 'lagos', 'LA', 'NG'),
    ('city', 'Badagry', 'badagry', 'lagos', 'LA', 'NG'),
    ('city', 'Bonny', 'bonny', 'rivers', 'RI', 'NG'),
    ('city', 'Sango-Ota', 'sango-ota', 'ogun', 'OG', 'NG'),
    ('city', 'Wudil', 'wudil', 'kano', 'KN', 'NG'),
    ('city', 'Zaria', 'zaria', 'kaduna', 'KD', 'NG'),
    ('city', 'Auchi', 'auchi', 'edo', 'ED', 'NG'),
    ('city', 'Warri', 'warri', 'delta', 'DE', 'NG'),
    ('city', 'Onitsha', 'onitsha', 'anambra', 'AN', 'NG'),
    ('city', 'Nnewi', 'nnewi', 'anambra', 'AN', 'NG'),
    ('city', 'Nsukka', 'nsukka', 'enugu', 'EN', 'NG'),
    ('city', 'Orlu', 'orlu', 'imo', 'IM', 'NG'),
    ('city', 'Eket', 'eket', 'akwa-ibom', 'AK', 'NG'),
    ('city', 'Ikom', 'ikom', 'cross-river', 'CR', 'NG'),
    ('city', 'Offa', 'offa', 'kwara', 'KW', 'NG'),
    ('city', 'Ogbomosho', 'ogbomosho', 'oyo', 'OY', 'NG'),
    ('city', 'Ile-Ife', 'ile-ife', 'osun', 'OS', 'NG'),
    ('city', 'Ondo City', 'ondo-city', 'ondo', 'ON', 'NG'),
    ('city', 'Owo', 'owo', 'ondo', 'ON', 'NG'),
    ('city', 'Bukuru', 'bukuru', 'plateau', 'PL', 'NG'),
    ('city', 'Gboko', 'gboko', 'benue', 'BE', 'NG'),
    ('city', 'Biu', 'biu', 'borno', 'BO', 'NG'),
    ('city', 'Daura', 'daura', 'katsina', 'KT', 'NG'),
    ('city', 'Tambuwal', 'tambuwal', 'sokoto', 'SO', 'NG'),
    ('city', 'Gwagwalada', 'gwagwalada', 'fct', 'FC', 'NG'),
    ('city', 'Kubwa', 'kubwa', 'fct', 'FC', 'NG'),
    ('area', 'Lekki', 'lekki', 'lagos', 'LA', 'NG'),
    ('area', 'Victoria Island', 'victoria-island', 'lagos', 'LA', 'NG'),
    ('area', 'Ikeja', 'ikeja', 'lagos', 'LA', 'NG'),
    ('area', 'Yaba', 'yaba', 'lagos', 'LA', 'NG'),
    ('area', 'Lagos Mainland', 'mainland', 'lagos', 'LA', 'NG'),
    ('area', 'Ikoyi', 'ikoyi', 'lagos', 'LA', 'NG'),
    ('area', 'Ajah', 'ajah', 'lagos', 'LA', 'NG'),
    ('area', 'Surulere', 'surulere', 'lagos', 'LA', 'NG'),
    ('area', 'Maryland', 'maryland', 'lagos', 'LA', 'NG'),
    ('area', 'Festac Town', 'festac', 'lagos', 'LA', 'NG'),
    ('area', 'Agege', 'agege', 'lagos', 'LA', 'NG'),
    ('area', 'Ilupeju', 'ilupeju', 'lagos', 'LA', 'NG'),
    ('area', 'Gbagada', 'gbagada', 'lagos', 'LA', 'NG'),
    ('area', 'Magodo', 'magodo', 'lagos', 'LA', 'NG'),
    ('area', 'Ojodu', 'ojodu', 'lagos', 'LA', 'NG'),
    ('area', 'Alimosho', 'alimosho', 'lagos', 'LA', 'NG'),
    ('area', 'Apapa', 'apapa', 'lagos', 'LA', 'NG'),
    ('area', 'Lekki Phase 1', 'lekki-phase-1', 'lagos', 'LA', 'NG'),
    ('area', 'Lekki Phase 2', 'lekki-phase-2', 'lagos', 'LA', 'NG'),
    ('area', 'Chevron Drive', 'chevron', 'lagos', 'LA', 'NG'),
    ('area', 'Sangotedo', 'sangotedo', 'lagos', 'LA', 'NG'),
    ('area', 'Ibeju-Lekki', 'ibeju-lekki', 'lagos', 'LA', 'NG'),
    ('area', 'Banana Island', 'banana-island', 'lagos', 'LA', 'NG'),
    ('area', 'Parkview', 'parkview', 'lagos', 'LA', 'NG'),
    ('area', 'Omole', 'omole', 'lagos', 'LA', 'NG'),
    ('area', 'Ogudu', 'ogudu', 'lagos', 'LA', 'NG'),
    ('area', 'Ketu', 'ketu', 'lagos', 'LA', 'NG'),
    ('area', 'Mushin', 'mushin', 'lagos', 'LA', 'NG'),
    ('area', 'Oshodi', 'oshodi', 'lagos', 'LA', 'NG'),
    ('area', 'Isolo', 'isolo', 'lagos', 'LA', 'NG'),
    ('area', 'Egbeda', 'egbeda', 'lagos', 'LA', 'NG'),
    ('area', 'Ikotun', 'ikotun', 'lagos', 'LA', 'NG'),
    ('area', 'Ajegunle', 'ajegunle', 'lagos', 'LA', 'NG'),
    ('area', 'Bariga', 'bariga', 'lagos', 'LA', 'NG'),
    ('area', 'Palmgrove', 'palmgrove', 'lagos', 'LA', 'NG'),
    ('area', 'Anthony', 'anthony', 'lagos', 'LA', 'NG'),
    ('area', 'Ojota', 'ojota', 'lagos', 'LA', 'NG'),
    ('area', 'Maitama', 'maitama', 'abuja', 'FC', 'NG'),
    ('area', 'Wuse', 'wuse', 'abuja', 'FC', 'NG'),
    ('area', 'Garki', 'garki', 'abuja', 'FC', 'NG'),
    ('area', 'Asokoro', 'asokoro', 'abuja', 'FC', 'NG'),
    ('area', 'Jabi', 'jabi', 'abuja', 'FC', 'NG'),
    ('area', 'Gwarinpa', 'gwarinpa', 'abuja', 'FC', 'NG'),
    ('area', 'Utako', 'utako', 'abuja', 'FC', 'NG'),
    ('area', 'Central Business District', 'cbd-abuja', 'abuja', 'FC', 'NG'),
    ('area', 'Life Camp', 'life-camp', 'abuja', 'FC', 'NG'),
    ('area', 'Lokogoma', 'lokogoma', 'abuja', 'FC', 'NG'),
    ('area', 'Lugbe', 'lugbe', 'abuja', 'FC', 'NG'),
    ('area', 'Karu', 'karu-abuja', 'abuja', 'FC', 'NG'),
    ('area', 'Nyanya', 'nyanya', 'abuja', 'FC', 'NG'),
    ('area', 'Kubwa Town', 'kubwa-town', 'abuja', 'FC', 'NG'),
    ('area', 'Bodija', 'bodija', 'ibadan', 'OY', 'NG'),
    ('area', 'UI / Ibadan North', 'ui-ibadan', 'ibadan', 'OY', 'NG'),
    ('area', 'Ring Road', 'ring-road', 'ibadan', 'OY', 'NG'),
    ('area', 'Challenge', 'challenge', 'ibadan', 'OY', 'NG'),
    ('area', 'Iwo Road', 'iwo-road', 'ibadan', 'OY', 'NG'),
    ('area', 'Dugbe', 'dugbe', 'ibadan', 'OY', 'NG'),
    ('area', 'Jericho', 'jericho', 'ibadan', 'OY', 'NG'),
    ('area', 'Akobo', 'akobo', 'ibadan', 'OY', 'NG'),
    ('area', 'GRA Port Harcourt', 'ph-gra', 'port-harcourt', 'RI', 'NG'),
    ('area', 'Trans Amadi', 'trans-amadi', 'port-harcourt', 'RI', 'NG'),
    ('area', 'Rumuola', 'rumuola', 'port-harcourt', 'RI', 'NG'),
    ('area', 'Rumuokoro', 'rumuokoro', 'port-harcourt', 'RI', 'NG'),
    ('area', 'Old GRA', 'old-gra-ph', 'port-harcourt', 'RI', 'NG'),
    ('area', 'Ada George', 'ada-george', 'port-harcourt', 'RI', 'NG'),
    ('area', 'Sabon Gari', 'sabon-gari', 'kano-city', 'KN', 'NG'),
    ('area', 'Nassarawa', 'nassarawa-kano', 'kano-city', 'KN', 'NG'),
    ('area', 'Fagge', 'fagge', 'kano-city', 'KN', 'NG'),
    ('area', 'Tarauni', 'tarauni', 'kano-city', 'KN', 'NG'),
    ('area', 'GRA Benin', 'benin-gra', 'benin-city', 'ED', 'NG'),
    ('area', 'Ugbowo', 'ugbowo', 'benin-city', 'ED', 'NG'),
    ('area', 'Ring Road Benin', 'ring-road-benin', 'benin-city', 'ED', 'NG'),
    ('area', 'Independence Layout', 'independence-layout', 'enugu-city', 'EN', 'NG'),
    ('area', 'New Haven', 'new-haven', 'enugu-city', 'EN', 'NG'),
    ('area', 'Trans-Ekulu', 'trans-ekulu', 'enugu-city', 'EN', 'NG'),
    ('area', 'Calabar South', 'calabar-south', 'calabar', 'CR', 'NG'),
    ('area', 'Marian', 'marian', 'calabar', 'CR', 'NG'),
    ('area', 'Ewet Housing', 'ewet-housing', 'uyo', 'AK', 'NG'),
    ('area', 'Aka Offot', 'aka-offot', 'uyo', 'AK', 'NG'),
    ('area', 'Tanke', 'tanke', 'ilorin', 'KW', 'NG'),
    ('area', 'G.R.A Ilorin', 'ilorin-gra', 'ilorin', 'KW', 'NG'),
    ('area', 'Ibara', 'ibara', 'abeokuta', 'OG', 'NG'),
    ('area', 'Lafenwa', 'lafenwa', 'abeokuta', 'OG', 'NG'),
    ('area', 'Alagbaka', 'alagbaka', 'akure', 'ON', 'NG'),
    ('area', 'Oba-Ile', 'oba-ile', 'akure', 'ON', 'NG'),
    ('area', 'Effurun', 'effurun', 'warri', 'DE', 'NG'),
    ('area', 'Warri GRA', 'warri-gra', 'warri', 'DE', 'NG'),
    ('area', 'Main Market', 'onitsha-main-market', 'onitsha', 'AN', 'NG'),
    ('area', 'GRA Onitsha', 'onitsha-gra', 'onitsha', 'AN', 'NG'),
    ('area', 'Rayfield', 'rayfield', 'jos', 'PL', 'NG'),
    ('area', 'Terminus', 'terminus-jos', 'jos', 'PL', 'NG'),
]

