import type { HostDiscovery } from "@/lib/types/hosts-discovery";

/** Placeholder IDs on demo cards only — not real DB host UUIDs. */
export const PLACEHOLDER_DISCOVER_HOST_ID_PREFIX =
  "00000000-0000-4000-8000-";

export function isPlaceholderDiscoverHostId(hostId: string): boolean {
  return hostId.startsWith(PLACEHOLDER_DISCOVER_HOST_ID_PREFIX);
}

/** Curated demo hosts when the discover API is empty (local / seed-less). */
export const DEMO_DISCOVER_HOSTS: HostDiscovery[] = [
  {
    host_id: "00000000-0000-4000-8000-000000000001",
    display_name: "DJ Maze",
    username: "djmaze",
    verified: true,
    legacy_tier: "Icon",
    legacy_status: "Icon",
    bio: "Afrobeats nights, Detty Fridays, and Mainland After Dark.",
    tagline: "Afrobeats nights, Detty Fridays, and Mainland After Dark.",
    avatar_url: "/demo/hosts/djmaze-avatar.svg",
    cover_url: null,
    primary_city: "Lagos",
    primary_category: "music",
    host_type: "music",
    upcoming_events_count: 6,
    completed_events_count: 42,
    verified_checkins_count: 1240,
    tickets_sold_count: 2840,
    average_rating: 4.8,
    review_count: 186,
    followers_count: 3200,
    vault_items_count: 8,
    sponsor_ready: true,
    next_upcoming_event: {
      title: "Afrobeats Night Live",
      slug: "afrobeats-night-live",
      start_datetime: "2026-07-25T20:00:00+01:00",
      city: "Lagos",
    },
    share_path: "/@djmaze",
  },
  {
    host_id: "00000000-0000-4000-8000-000000000002",
    display_name: "Lagos Comedy Hub",
    username: "lagoscomedyhub",
    verified: true,
    legacy_tier: "Established",
    legacy_status: "Established",
    bio: "Island comedy nights and open mic culture.",
    tagline: "Island comedy nights and open mic culture.",
    avatar_url: "/demo/hosts/lagoscomedyhub-avatar.svg",
    cover_url: null,
    primary_city: "Lagos",
    primary_category: "comedy",
    host_type: "comedy",
    upcoming_events_count: 3,
    completed_events_count: 28,
    verified_checkins_count: 890,
    tickets_sold_count: 1950,
    average_rating: 4.7,
    review_count: 112,
    followers_count: 1800,
    vault_items_count: 4,
    sponsor_ready: true,
    next_upcoming_event: {
      title: "Laugh Lagos Live",
      slug: "demo-lagos-comedy-jam",
      start_datetime: "2026-07-24T19:00:00+01:00",
      city: "Lagos",
    },
    share_path: "/@lagoscomedyhub",
  },
  {
    host_id: "00000000-0000-4000-8000-000000000003",
    display_name: "Mainland Vibes",
    username: "mainlandvibes",
    verified: true,
    legacy_tier: "Rising",
    legacy_status: "Rising",
    bio: "Food & culture fests and Lagos Creative Market.",
    tagline: "Food & culture fests and Lagos Creative Market.",
    avatar_url: "/demo/hosts/mainlandvibes-avatar.svg",
    cover_url: null,
    primary_city: "Lagos",
    primary_category: "lifestyle",
    host_type: "lifestyle",
    upcoming_events_count: 2,
    completed_events_count: 11,
    verified_checkins_count: 420,
    tickets_sold_count: 880,
    average_rating: 4.6,
    review_count: 48,
    followers_count: 640,
    vault_items_count: 0,
    sponsor_ready: false,
    next_upcoming_event: {
      title: "Mainland Summer Edition",
      slug: "mainland-summer-edition",
      start_datetime: "2026-08-02T16:00:00+01:00",
      city: "Lagos",
    },
    share_path: "/@mainlandvibes",
  },
  {
    host_id: "00000000-0000-4000-8000-000000000004",
    display_name: "Tech Connect Africa",
    username: "techconnectafrica",
    verified: true,
    legacy_tier: "Established",
    legacy_status: "Established",
    bio: "Founders mixers and product builder nights.",
    tagline: "Founders mixers and product builder nights.",
    avatar_url: "/demo/hosts/techconnectafrica-avatar.svg",
    cover_url: null,
    primary_city: "Lagos",
    primary_category: "tech",
    host_type: "tech",
    upcoming_events_count: 4,
    completed_events_count: 19,
    verified_checkins_count: 610,
    tickets_sold_count: 1420,
    average_rating: 4.9,
    review_count: 74,
    followers_count: 2100,
    vault_items_count: 5,
    sponsor_ready: true,
    next_upcoming_event: {
      title: "Founders Mixer",
      slug: "founders-mixer",
      start_datetime: "2026-07-30T18:30:00+01:00",
      city: "Lagos",
    },
    share_path: "/@techconnectafrica",
  },
  {
    host_id: "00000000-0000-4000-8000-000000000005",
    display_name: "Praise Experience",
    username: "praiseexperience",
    verified: true,
    legacy_tier: "Rising",
    legacy_status: "Rising",
    bio: "Worship nights under the stars.",
    tagline: "Worship nights under the stars.",
    avatar_url: "/demo/hosts/praiseexperience-avatar.svg",
    cover_url: null,
    primary_city: "Ibadan",
    primary_category: "gospel",
    host_type: "gospel",
    upcoming_events_count: 1,
    completed_events_count: 7,
    verified_checkins_count: 310,
    tickets_sold_count: 540,
    average_rating: 4.9,
    review_count: 36,
    followers_count: 920,
    vault_items_count: 2,
    sponsor_ready: false,
    next_upcoming_event: {
      title: "Praise Under the Stars",
      slug: "praise-under-the-stars",
      start_datetime: "2026-08-08T19:00:00+01:00",
      city: "Ibadan",
    },
    share_path: "/@praiseexperience",
  },
];

export const DEMO_LEGACY_QUICK_LINKS = [
  { label: "DJ Maze", username: "djmaze" },
  { label: "Lagos Comedy Hub", username: "lagoscomedyhub" },
  { label: "Mainland Vibes", username: "mainlandvibes" },
  { label: "Tech Connect Africa", username: "techconnectafrica" },
  { label: "Praise Experience", username: "praiseexperience" },
] as const;
